### PR TITLE
fix(add-on): Re-add the output suggesting ddev restart after add-on, fixes #8088

### LINKED ISSUE #8088: `ddev add-on get` should prompt to `ddev restart`
### Preliminary checklist

- [x] I am using the latest stable version of DDEV (see [upgrade guide](https://docs.ddev.com/en/stable/users/install/ddev-upgrade/))
- [x] I have searched [existing issues](https://github.com/ddev/ddev/issues)
- [x] I have checked the [troubleshooting guide](https://docs.ddev.com/en/stable/users/usage/troubleshooting/)
- [x] I have run `ddev utility test` or at least `ddev utility diagnose` to include output below

### Output of `ddev utility test` or `ddev utility diagnose`

<details><summary>Expand `ddev utility test` diagnostic information</summary>

```
[COPY-PASTE HERE THE OUTPUT OF `ddev utility test`]
```
</details>

### Expected Behavior

DDEV for a really long time said to restart after add-on installation:

addon-get.go:
> util.Success("\nInstalled DDEV add-on %s, use `ddev restart` to enable.", sourceRepoArg)

### Actual Behavior

Now it was lost in 42229020e1ec82b4a88e4677ac57e2c8939abf8c

We should put that line back in.

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by rfay**
## The Issue

- #8088
- https://github.com/ddev/ddev-drupal-contrib/issues/162#issuecomment-3836463256

We lost the prompt to `ddev restart` after `ddev add-on get` in 
* https://github.com/ddev/ddev/pull/7523

## How This PR Solves The Issue

Add the prompt back in

## Manual Testing Instructions

`ddev add-on get <something>` and look for the prompt to restart

image

### CODE REVIEW

File: cmd/ddev/cmd/addon-get.go [hunk 1]
```diff
@@ -298,7 +297,7 @@ ddev add-on get /path/to/tarball.tar.gz
 		if argType == "github" {
 			util.Success("Please read instructions for this add-on at the source repo at\nhttps://github.com/%v/%v\nPlease file issues and create pull requests there to improve it.", owner, repo)
 		}
-		output.UserOut.WithField("raw", manifest).Printf("Installed %s:%s from %s", manifest.Name, manifest.Version, manifest.Repository)
+		util.Success("Installed %[1]s:%[2]s from %[3]s\nUse `ddev restart` to enable %[1]s:%[2]s.", manifest.Name, manifest.Version, manifest.Repository)
```
Comment (stasadev) [inline cmd/ddev/cmd/addon-get.go]: Without `raw`, it breaks:

```go
// getManifestFromLogs returns the manifest built from 'raw' section of
// ddev add-on get <project> -j output
func getManifestFromLogs(t *testing.T, jsonOut string) map[string]interface{} {
	assert := asrt.New(t)

	logItems, err := unmarshalJSONLogs(jsonOut)
	require.NoError(t, err)
	data := logItems[len(logItems)-1]
	assert.EqualValues(data["level"], "info")

	m, ok := data["raw"].(map[string]interface{})
	require.True(t, ok)
	return m
}
```
