### PR TITLE
fix(laravel): don't edit database config in `.env` when there's no database

### LINKED ISSUE #7577: Laravel type overwrites .env DB_HOST when using `omit_containers: [db]`
### Preliminary checklist

- [x] I am using the latest stable version of DDEV (see [upgrade guide](https://docs.ddev.com/en/stable/users/install/ddev-upgrade/))
- [x] I have searched [existing issues](https://github.com/ddev/ddev/issues)
- [x] I have checked the [troubleshooting guide](https://docs.ddev.com/en/stable/users/usage/troubleshooting/)
- [x] I have run `ddev debug test` to include output below

# DDEV Laravel Type Overwrites External Database Configuration

## Issue Description

When using DDEV's `type: laravel` with an external database from another DDEV project, `ddev restart` overwrites the `.env` file's database configuration, causing connection issues and unpredictable database routing.

## Environment

- **DDEV Version**: v1.24.7
- **Project Type**: `laravel`
- **OS**: Linux (Docker v28.3.3, Docker Compose v2.38.2)
- **Setup**: Multiple DDEV projects on the same machine

### Setup
- **Project A** (`ecommerce`): Laravel application that needs to connect to external database
- **Project B** (`generate`): Contains the database service (`ddev-generate-db`)
- **Cross-project communication**: Configured via `.ddev/docker-compose.communicate.yaml`

### Expected Behavior
When we configure our `.env` and `.env.example` files with:
```bash
DB_HOST="ddev-generate-db"
```

This configuration should persist after `ddev restart`.

### Actual Behavior
After `ddev restart`, DDEV's Laravel type automatically overwrites the `.env` file, changing:
```bash
# Before restart (our configuration)
DB_HOST="ddev-generate-db"

# After restart (DDEV overwrites)
DB_HOST="db"
```

### Consequences
1. **Connection failures** when the external database is required
2. **Unpredictable database routing** - when multiple DDEV projects run simultaneously, each with their own `db` service, Docker's service discovery appears to load-balance or round-robin between different `db` containers
3. **Data inconsistency** - requests randomly connect to different databases
4. **Development environment instability**

## Reproduction Steps

1. Create two DDEV projects:
   ```bash
   # Project 1: Database provider
   mkdir generate && cd generate
   ddev config --project-type=laravel --project-name=generate
   ddev start

   # Project 2: Database consumer
   mkdir ecommerce && cd ecommerce
   ddev config --project-type=laravel --project-name=ecommerce
   ```

2. Configure cross-project communication in `ecommerce/.ddev/docker-compose.communicate.yaml`:
   ```yaml
   services:
     web:
       external_links:
         - "ddev-generate-db:generate-db"
   ```

3. Set external database in `ecommerce/.env`:
   ```bash
   DB_HOST="ddev-generate-db"
   ```

4. Verify connection works:
   ```bash
   ddev exec php artisan tinker --execute="echo config('database.connections.mysql.host');"
   # Output: ddev-generate-db ✅
   ```

5. Restart DDEV:
   ```bash
   ddev restart
   ```

6. Check `.env` file:
   ```bash
   cat .env | grep DB_HOST
   # Output: DB_HOST="db" ❌ (overwritten by DDEV)
   ```

## Current Workaround

We can override the `.env` file using `web_environment` in `.ddev/config.yaml`:

```yaml
web_environment:
  - DB_HOST=ddev-generate-db
  - DB_PORT=3306
  - DB_DATABASE=db
  - DB_USERNAME=db
  - DB_PASSWORD=db
```

This works because Laravel's `env()` function prioritizes actual environment variables over `.env` file values.

**Verification:**
```bash
# .env file still shows (DDEV's override)
DB_HOST="db"

# But environment variables show (our override)
ddev exec env | grep DB_HOST
# Output: DB_HOST=ddev-generate-db

# Laravel uses the environment variable
ddev exec php artisan tinker --execute="echo config('database.connections.mysql.host');"
# Output: ddev-generate-db ✅
```

## Root Cause Analysis

The issue is in the `laravelPostStartAction` function in `pkg/ddevapp/laravel.go`:

```go
func laravelPostStartAction(app *DdevApp) error {
    // ... existing code ...

    envMap := map[string]string{
        "APP_URL":       app.GetPrimaryURL(),
        "DB_HOST":       "db",  // ← Always hardcoded to "db"
        "DB_PORT":       port,
        "DB_DATABASE":   "db",
        "DB_USERNAME":   "db",
        "DB_PASSWORD":   "db",
        "DB_CONNECTION": dbConnection,
        // ... other settings ...
    }
    err = WriteProjectEnvFile(envFilePath, envMap, envText)
    // ...
}
```

The function **always** sets `DB_HOST` to `"db"` without checking if an external database configuration exists.

## Proposed Solution

**Request**: DDEV should preserve database configuration when `DB_HOST` starts with `ddev-` prefix, indicating intentional cross-project communication.

**Proposed Code Change:**
```go
func laravelPostStartAction(app *DdevApp) error {
    // ... existing code to read .env file ...

    // Check if DB_HOST is already set to a ddev- prefixed host
    existingDBHost := ""
    if envText != "" {
        // Parse existing DB_HOST from envText
        if matches := regexp.MustCompile(`DB_HOST\s*=\s*"?([^"\s]+)"?`).FindStringSubmatch(envText); len(matches) > 1 {
            existingDBHost = matches[1]
        }
    }

    // Default database host
    dbHost := "db"

    // Preserve ddev- prefixed hosts (external DDEV databases)
    if strings.HasPrefix(existingDBHost, "ddev-") {
        dbHost = existingDBHost
    }

    envMap := map[string]string{
        "APP_URL":       app.GetPrimaryURL(),
        "DB_HOST":       dbHost,  // ← Use preserved or default value
        "DB_PORT":       port,
        "DB_DATABASE":   "db",
        "DB_USERNAME":   "db",
        "DB_PASSWORD":   "db",
        "DB_CONNECTION": dbConnection,
        // ... other settings ...
    }

    // ... rest of function ...
}
```

**Logic:**
```bash
# Current behavior: Always overwrite
DB_HOST="anything" → DB_HOST="db"

# Proposed behavior: Respect ddev- prefixed hosts
DB_HOST="ddev-generate-db" → DB_HOST="ddev-generate-db" (preserved)
DB_HOST="localhost" → DB_HOST="db" (overwrite as usual)
DB_HOST="custom-host" → DB_HOST="db" (overwrite as usual)
```

## Alternative Solutions

1. **Configuration flag** to disable `.env` database overwriting:
   ```yaml
   # .ddev/config.yaml
   laravel_preserve_db_config: true
   ```

2. **Detect external_links** and skip overwriting when external database links exist

3. **Warning instead of overwrite** when non-standard database hosts are detected

## Impact

This affects any Laravel project using:
- Cross-project database sharing
- External database services
- Custom database configurations
- Multi-project development environments

The current behavior forces developers to use workarounds and makes DDEV's Laravel type less flexible for complex development setups.

### Expected Behavior

See description.

### Actual Behavior

See description.

### Steps To Reproduce

See description.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by cyppe**
## Issue

- Fixes #7577

Laravel projects using external databases have their `.env` configuration overwritten by DDEV on restart, breaking cross-project database connections.

## How This PR Solves The Issue

- Skip database configuration when `db` container is omitted (following Symfony pattern)
- Maintain backward compatibility for standard setups

## Manual Testing Instructions

Follow Laravel SQLite quickstart without adding `--disable-settings-management=true`

```
mkdir my-laravel-site && cd my-laravel-site
ddev config --project-type=laravel --docroot=public --omit-containers=db
ddev start
ddev composer create-project "laravel/laravel:^12"
cat .env | grep DB
```

v1.24.7:

```
$ ddev composer create-project "laravel/laravel:^12"
...
> @php -r "file_exists('database/database.sqlite') || touch('database/database.sqlite');"
> @php artisan migrate --graceful --ansi

   WARN  SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo for db failed: Name or service not known (Connection: mariadb, SQL: select exists (select 1 from information_schema.tables where table_schema = schema() and table_name = 'migrations' and table_type in ('BASE TABLE', 'SYSTEM VERSIONED')) as `exists`).  

ddev composer create-project was successful. 

$ curl -I https://my-laravel-site.ddev.site/
HTTP/2 500 
cache-control: no-cache, private
content-type: text/html; charset=UTF-8
date: Tue, 09 Sep 2025 11:50:02 GMT
server: nginx
```

This PR (look inside `.env`, it should use `DB_CONNECTION=sqlite`):

```
$ ddev composer create-project "laravel/laravel:^12"
...
> @php artisan migrate --graceful --ansi

   INFO  Preparing database.  

  Creating migration table ...................................... 15.17ms DONE

   INFO  Running migrations.  

  0001_01_01_000000_create_users_table .......................... 30.76ms DONE
  0001_01_01_000001_create_cache_table .......................... 10.25ms DONE
  0001_01_01_000002_create_jobs_table ........................... 24.79ms DONE

ddev composer create-project was successful.

$ curl -I https://my-laravel-site.ddev.site/
HTTP/2 200 
cache-control: no-cache, private
content-type: text/html; charset=UTF-8
date: Tue, 09 Sep 2025 11:51:59 GMT
server: nginx
set-cookie: XSRF-TOKEN=eyJpdiI6InMrQUxMWXpxMUpaMzdCcmVITytQS3c9PSIsInZhbHVlIjoiYVhmczI2QTcvMjBvcWk3ZnF1Qkc2cmFRSDNNUEl4YjN2Q2JaaWdzc3IrUkN0M0pLVURHVUtmaGJzMFhoV1lCck5mTk9JTU1DbXpDMXJuaDlTSUtkQUdFa0lQQXVTa0c0ekhkZERYeHBDTXlRaHVzSTcrUVBTRkJPbDJLSzhqQ3ciLCJtYWMiOiI5ZWI4Njc4YzQyM2FkMmFkN2FlNzljMzUzYjI3NjY3NmI3OTI1YTFmZmQ1Mjk0NjZjMzRlZDJlMGIzZDg0MWRjIiwidGFnIjoiIn0%3D; expires=Tue, 09 Sep 2025 13:51:59 GMT; Max-Age=7200; path=/; secure; samesite=lax
set-cookie: laravel-session=eyJpdiI6IktiaFVBNjhibThBN05rc3haZ3UzS2c9PSIsInZhbHVlIjoiaHRCVk1yZWJjQ3BhVEhXc1NTdGRoWnlzK0pCKzE2S2I1RVRmbUZ6UVFvWjF5cW91NFZzQ0lySWsxVUJUNmF1cXhEdUloNTN2UlVSUnhyUC91bUF4MmFGUkNZam1teWJHU2htVjBWbFF5dTd4bFhibnRkT1JRNEtsUDJTSEQ2bHUiLCJtYWMiOiIxOTlkZDdkNzkzNDgzNjUwZGFiZTBhM2VmMDQzZjQ1ZDM4MjBkM2EwMTYzMDM5YzJmMjMxZWE1ZGE4NzU0NzIwIiwidGFnIjoiIn0%3D; expires=Tue, 09 Sep 2025 13:51:59 GMT; Max-Age=7200; path=/; secure; httponly; samesite=lax
vary: Accept-Encoding
```

## Automated Testing Overview

Added new tests.

### CODE REVIEW

File: pkg/ddevapp/laravel.go [hunk 1]
```diff
@@ -78,3 +88,10 @@ func laravelPostStartAction(app *DdevApp) error {
 
 	return nil
 }
+
+// hasDdevPrefixedHost checks if the .env file contains a DB_HOST with ddev- prefix
+func hasDdevPrefixedHost(envFilePath string) bool {
+	envMap, _, _ := ReadProjectEnvFile(envFilePath)
+	existingDBHost := envMap["DB_HOST"]
+	return existingDBHost != "" && strings.HasPrefix(existingDBHost, "ddev-")
+}
```
Comment (stasadev) [inline pkg/ddevapp/laravel.go]: It works, but I'm not sure if `hasDdevPrefixedHost` is worth it, since it's unexpected, undocumented, and not really tested.

If we add it, there will be no way back without breaking changes, because people will start depending on it. We should consider it carefully.

If you want this PR merged in the next release cycle (~2 weeks), let's remove `hasDdevPrefixedHost` from here, keep only the change for `--omit-containers=db`, and discuss whether we want something like this in the issue queue.

**Review by stasadev — CHANGES_REQUESTED** [review]
Thank you @cyppe, especially for the new tests.

This change will significantly improve the logic for our Laravel SQLite quickstart https://docs.ddev.com/en/stable/users/quickstart/#laravel-composer-sqlite

We will be able to remove `--disable-settings-management=true` from that quickstart in a few months (after most of DDEV users are using v1.24.8+)

Let's make it a bit simpler without `hasDdevPrefixedHost`, and I'll approve and merge it.

**Comment by rfay** [comment]
Rebased

**Review by stasadev — APPROVED** [review]
I removed custom logic for `ddev-` prefixes, updated tests and quickstarts.

File: docs/content/users/quickstart.md [hunk 2]
```diff
@@ -509,6 +509,7 @@ The Laravel project type can be used for [StarterKits](https://laravel.com/docs/
 
     ```bash
     mkdir my-laravel-site && cd my-laravel-site
+    # If you're using DDEV v1.24.8+, you don't need --disable-settings-management=true
     ddev config --project-type=laravel --docroot=public --omit-containers=db --disable-settings-management=true
```
Comment (tyler36) [inline docs/content/users/quickstart.md]:
```suggestion
    # If you're using  an older version of DDEV (<=v1.24.7),
    # you need to add `--disable-settings-management=true`
    ddev config --project-type=laravel --docroot=public --omit-containers=db
```

File: docs/content/users/quickstart.md [hunk 3]
```diff
@@ -518,6 +519,7 @@ The Laravel project type can be used for [StarterKits](https://laravel.com/docs/
     To switch an existing Laravel project to SQLite:
 
     ```bash
+    # If you're using DDEV v1.24.8+, you don't need --disable-settings-management=true
     ddev config --project-type=laravel --docroot=public --omit-containers=db --disable-settings-management=true
```
Comment (tyler36) [inline docs/content/users/quickstart.md]:
```suggestion
    # If you're using  an older version of DDEV (<=v1.24.7),
    you need to add `--disable-settings-management=true`
    ddev config --project-type=laravel --docroot=public --omit-containers=db
```

File: docs/content/users/quickstart.md (hunk 2 above)
Comment (tyler36) [reply docs/content/users/quickstart.md]: The docs should reflect the current version. The additional flags is required when developers are not on the latest version.

File: docs/content/users/quickstart.md (hunk 3 above)
Comment (tyler36) [reply docs/content/users/quickstart.md]: The docs should reflect the current version. The additional flags is required when developers are not on the latest version.

**Review by tyler36 — CHANGES_REQUESTED** [review]
Works as intended.

Minor suggestion. The docs should reflect the current workflow and not require addition flags `--disable-settings-management=true`.

## Test

### Current DDEV 

1. Check version

```shell
$ ddev -v
ddev version v1.24.7
```

2. Install new Laravel project

```shell
mkdir my-laravel-site && cd my-laravel-site
ddev config --project-type=laravel --docroot=public --omit-containers=db 
ddev start
ddev composer create-project "laravel/laravel:^12"
```

3.  Check `.env` is set to Sqlite ❌ 

```shell
$ cat .env | grep DB
DB_CONNECTION="mariadb"
DB_HOST="db"
DB_PORT="3306"
DB_DATABASE="db"
DB_USERNAME="db"
DB_PASSWORD="db"
```

### This PR 

1. Check version

```shell
$ ddev -v
ddev version v1.24.7-79-g650a18b1b
```

2. Install new Laravel project

```shell
mkdir my-laravel-site && cd my-laravel-site
ddev config --project-type=laravel --docroot=public --omit-containers=db 
ddev start
ddev composer create-project "laravel/laravel:^12"
```

3.  Check `.env` is set to Sqlite ✅ 

```shell
$ cat .env | grep DB
DB_CONNECTION=sqlite
# DB_HOST=127.0.0.1
# DB_PORT=3306
# DB_DATABASE=laravel
# DB_USERNAME=root
# DB_PASSWORD=
```

File: docs/content/users/quickstart.md (hunk 2 above)
Comment (stasadev) [reply docs/content/users/quickstart.md]: I thought about changing the default later, but I agree, let's do it now.

File: docs/content/users/quickstart.md [hunk 4]
```diff
@@ -518,7 +520,9 @@ The Laravel project type can be used for [StarterKits](https://laravel.com/docs/
     To switch an existing Laravel project to SQLite:
 
     ```bash
-    ddev config --project-type=laravel --docroot=public --omit-containers=db --disable-settings-management=true
+    # If you're using  an older version of DDEV (<=v1.24.7),
+    you need to add `--disable-settings-management=true`
```
Comment (stasadev) [inline docs/content/users/quickstart.md]:
```suggestion
    # you need to add `--disable-settings-management=true`
```

File: docs/content/users/quickstart.md [hunk 5]
```diff
@@ -518,7 +520,9 @@ The Laravel project type can be used for [StarterKits](https://laravel.com/docs/
     To switch an existing Laravel project to SQLite:
 
     ```bash
-    ddev config --project-type=laravel --docroot=public --omit-containers=db --disable-settings-management=true
+    # If you're using  an older version of DDEV (<=v1.24.7),
```
Comment (stasadev) [inline docs/content/users/quickstart.md]:
```suggestion
    # If you're using an older version of DDEV (<=v1.24.7),
```

File: docs/content/users/quickstart.md [hunk 6]
```diff
@@ -509,7 +509,9 @@ The Laravel project type can be used for [StarterKits](https://laravel.com/docs/
 
     ```bash
     mkdir my-laravel-site && cd my-laravel-site
-    ddev config --project-type=laravel --docroot=public --omit-containers=db --disable-settings-management=true
+    # If you're using  an older version of DDEV (<=v1.24.7),
```
Comment (stasadev) [inline docs/content/users/quickstart.md]:
```suggestion
    # If you're using an older version of DDEV (<=v1.24.7),
```

File: docs/content/users/quickstart.md [hunk 7]
```diff
@@ -509,7 +509,7 @@ The Laravel project type can be used for [StarterKits](https://laravel.com/docs/
 
     ```bash
     mkdir my-laravel-site && cd my-laravel-site
-    # If you're using  an older version of DDEV (<=v1.24.7),
+    # If you're using an older version of DDEV (<=v1.24.7),
```
Comment (rfay) [inline docs/content/users/quickstart.md]: I'm reluctant to add version specs to the docs that get out of date so quickly. I wonder if there's another technique to work on this problem.

Comment (stasadev) [reply docs/content/users/quickstart.md]: Another way is not to update the quickstart, as we did with `ddev composer create-project`.
Wait a few months and only do it later.

Comment (rfay) [reply docs/content/users/quickstart.md]: OK to do it and set an issue and a todo I guess. Can be added to the v1.25.0 todos. Maybe we should start future release todo issues earlier and have a way to handle this.

Comment (stasadev) [reply docs/content/users/quickstart.md]: I reverted the changes to the docs, and added it to v1.25.0 todos.

Comment (tyler36) [reply docs/content/users/quickstart.md]: Thank you.

**Review by tyler36 — APPROVED** [review]
