### PR TITLE
fix(config): replace composer_version 1 option with 2.2 (LTS), fixes #8084

### LINKED ISSUE #8084: Remove `composer_version:  1` option, since Packagist no longer supports it
### Preliminary checklist

- [x] I am using the latest stable version of DDEV (see [upgrade guide](https://docs.ddev.com/en/stable/users/install/ddev-upgrade/))
- [x] I have searched [existing issues](https://github.com/ddev/ddev/issues)
- [x] I have checked the [troubleshooting guide](https://docs.ddev.com/en/stable/users/usage/troubleshooting/)
- [x] I have run `ddev utility test` or at least `ddev utility diagnose` to include output below

### Output of `ddev utility test` or `ddev utility diagnose`

<details><summary>Expand `ddev utility test` diagnostic information</summary>

```
[COPY-PASTE HERE THE OUTPUT OF `ddev utility test`]
```
</details>

### Expected Behavior

DDEV should be in sync with external providers

### Actual Behavior

We still support `composer_version: 1` but packagist doesn't

`"warning": "Support for Composer 1 has been shutdown on September 1st 2025. You should upgrade to Composer 2. See https://blog.packagist.com/shutting-down-packagist-org-support-for-composer-1-x/",`

I think that means we should remove the option? 

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by jonesrussell**
## The Issue

- Fixes #8084

Packagist no longer supports Composer 1 (as of September 2025). DDEV still allowed `composer_version: "1"`, which is no longer useful and can confuse users.

## How This PR Solves The Issue

- **Migration:** When config is loaded, if `composer_version` is `"1"`, it is migrated in memory to `"2.2"` (same pattern as other deprecated options like UploadDir). A one-time warning tells the user to run `ddev config --auto` to update `.ddev/config.yaml`. Existing projects keep working and the next config write persists the change.
- **CLI:** Removed `"1"` from the `--composer-version` flag help and from shell completion so it is no longer offered.
- **Docs:** Removed `"1"` from the configuration reference, command reference, and any composer version option lists.
- **Tests:** Updated Composer 1 test in `TestComposerVersion` and `TestComposerVersionConfig`.
- **Build:** No change to build logic; the Dockerfile comment was updated to stop mentioning major version `1`.

## Manual Testing Instructions

1. **New projects:** Run `ddev config --composer-version=2` (or omit for default). Confirm `"1"` is not offered in tab completion for `--composer-version`.
2. **Existing project with `composer_version: "1"`:** Set `composer_version: "1"` in `.ddev/config.yaml`, run `ddev start` (or any command that loads config). Confirm the warning about Packagist and that the project runs with Composer 2.2. Run `ddev config --auto` and confirm the config file now has `composer_version: "2.2"`.
3. **Docs:** Skim the updated config and command docs and confirm `"1"` is no longer listed as a valid value.

## Automated Testing Overview

- `TestComposerVersion` and `TestComposerVersionConfig` no longer use `"1"`; they cover default, `"2"`, `"2.2"`, explicit versions, and keywords.
- `autocompletion_test.go` updated so the expected `--composer-version` completion list no longer includes `"1"`.

## Release/Deployment Notes

No deployment changes. Users with `composer_version: "1"` in config will see a one-time warning and will use Composer 2 until they run `ddev config`, which updates the file. New users cannot select Composer 1.

### CODE REVIEW

File: pkg/ddevapp/config.go [hunk 1]
```diff
@@ -1456,7 +1465,7 @@ RUN (timeout %d apt-get update || true) && DEBIAN_FRONTEND=noninteractive apt-ge
 		}
 
 		// Major and minor versions have to be provided as option so add '--' prefix.
-		// E.g. a major version can be 1 or 2, a minor version 2.2 or 2.1 etc.
+		// E.g. a major version can be 2, a minor version 2.2 or 2.1 etc.
```
Comment (rfay) [inline pkg/ddevapp/config.go]: I think we can't use 2.1, right? IIRC the only options are LTS (only 2.2 at this time), 2 (major), or a specific full version?

```
self-update [-r|--rollback] [--clean-backups] [--no-progress] [--update-keys] [--stable] [--preview] [--snapshot] [--1] [--2] [--2.2] [--set-channel-only] [--] [<version>]
```

So 2, 2.2, or a specific version like 2.8.5 (and the test below shows those options)

There is no "minor version" option, only "LTS version"

Comment (rfay) [reply pkg/ddevapp/config.go]:
```suggestion
		// E.g. version can be 2, an LTS version (2.2 only) or full version like 2.9.5
```

**Review by rfay — APPROVED** [review]
This is great, and I'm willing to have it go in this way, but it doesn't do what's expected if .ddev/config.yaml has

```
composer_version:  "1.10.25"
```

In that case, it installs composer 1.10.25, which of course doesn't work.

**Comment by stasadev** [comment]
> This is great, and I'm willing to have it go in this way, but it doesn't do what's expected if .ddev/config.yaml has
> 
> ```
> composer_version:  "1.10.25"
> ```
> 
> In that case, it installs composer 1.10.25, which of course doesn't work.

Thank you, should be good now.
