### PR TITLE
fix: start container only after attach in `ddev auth ssh`, fixes #7664

### LINKED ISSUE #7664: `ddev auth ssh` hangs on Windows with WSL2
### Preliminary checklist

- [x] I am using the latest stable version of DDEV (see [upgrade guide](https://docs.ddev.com/en/stable/users/install/ddev-upgrade/))
- [x] I have searched [existing issues](https://github.com/ddev/ddev/issues)
- [x] I have checked the [troubleshooting guide](https://docs.ddev.com/en/stable/users/usage/troubleshooting/)
- [x] I have run `ddev debug test` to include output below

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

```


======== Output file will be in /tmp/ddev-debug-test.txt ========


======== ddev installation alternate locations: ========
/home/linuxbrew/.linuxbrew/bin/ddev



======== project configuration via ddev debug configyaml ========
# Complete processed project configuration:
additional_fqdns: []
additional_hostnames: []
composer_version: "2"
corepack_enable: true
database:
    type: mysql
    version: "8.0"
default_container_timeout: "120"
disable_settings_management: true
docroot: htdocs
hooks:
    post-start:
        - exec: sudo sed -i 's/<policy domain="coder" rights="none" pattern="PDF" \/>/<policy domain="coder" rights="read|write" pattern="PDF" \/>/g' /etc/ImageMagick-6/policy.xml
        - exec-host: '[ -d ''vendor/apache-solr-for-typo3/solr'' ] && ddev solrctl apply || (ddev composer install --no-interaction --quiet && ddev solrctl apply)'
        - exec-host: ddev auth ssh
name: typo3-contribute
nodejs_version: "22"
php_version: "8.3"
project_tld: ddev.site
timezone: Europe/Vienna
type: typo3
use_dns_when_possible: true
webimage: ddev/ddev-webserver:v1.24.8
webimage_extra_packages:
    - cron
    - dnsutils
    - pv
    - webp
webserver_type: apache-fpm
xdebug_enabled: false



======== existing project customizations ========
.ddev/docker-compose.override.yaml
.ddev/mutagen/mutagen.yml
.ddev/web-build/Dockerfile.ddev-cron


======== installed DDEV add-ons ========
┌────────────┬─────────┬──────────────────────┬───────────────────────────┐
│ ADD-ON     │ VERSION │ REPOSITORY           │ DATE INSTALLED            │
├────────────┼─────────┼──────────────────────┼───────────────────────────┤
│ typo3-solr │ 1.1.1   │ ddev/ddev-typo3-solr │ 2025-07-21T12:59:35+02:00 │
└────────────┴─────────┴──────────────────────┴───────────────────────────┘



======== WSL2 information ========
WSL version=WSL-Version: 2.4.11.0
Kernelversion: 5.15.167.4-1
WSLg-Version: 1.0.65
MSRDC-Version: 1.2.5716
Direct3D-Version: 1.611.1-81528511
DXCore-Version: 10.0.26100.1-240331-1435.ge-release
Windows-Version: 10.0.26100.6584
WSL2 networking mode=nat


======== mutagen situation ========
looking for #ddev-generated in mutagen.yml in project /home/andreas/projects/typo3-contribute

MODIFIED .ddev/mutagen/mutagen.yml found


======== Creating dummy project named tryddevproject-14541 in ../tryddevproject-14541 ========
Creating a new DDEV project config in the current directory (/home/andreas/projects/tryddevproject-14541)
Once completed, your configuration will be written to /home/andreas/projects/tryddevproject-14541/.ddev/config.yaml

Configuring a 'php' project named 'tryddevproject-14541' with docroot 'web' at '/home/andreas/projects/tryddevproject-14541/web'.
For full details use 'ddev describe'.
Configuration complete. You may now run 'ddev start'.


======== OS Information (uname -a) ========
Linux LS-PC-42 5.15.167.4-microsoft-standard-WSL2 #1 SMP Tue Nov 5 00:21:55 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux


======== User information (id -a) ========
uid=1000(andreas) gid=1000(andreas) groups=1000(andreas),4(adm),20(dialout),24(cdrom),25(floppy),27(sudo),29(audio),30(dip),44(video),46(plugdev),100(users),107(netdev),1001(docker)


======== DDEV version ========
 ITEM              VALUE
 DDEV version      v1.24.8
 architecture      amd64
 cgo_enabled       0
 db                ddev/ddev-dbserver-mariadb-10.11:v1.24.8
 ddev-environment  wsl2
 ddev-ssh-agent    ddev/ddev-ssh-agent:v1.24.8
 docker            28.4.0
 docker-api        1.51
 docker-compose    v2.39.3
 docker-platform   docker-desktop
 global-ddev-dir   /home/andreas/.ddev
 go-version        go1.25.1
 mutagen           0.18.1
 os                linux
 router            ddev/ddev-traefik-router:v1.24.8
 web               ddev/ddev-webserver:v1.24.8
 xhgui-image       ddev/ddev-xhgui:v1.24.8



======== proxy settings ========

  HTTP_PROXY=''
  http_proxy=''
  HTTPS_PROXY=''
  https_proxy=''
  NO_PROXY=''
  no_proxy=''



======== DDEV global info ========
developer-mode=false
fail-on-hook-fail=false
instrumentation-opt-in=false
instrumentation-queue-size=0
instrumentation-reporting-interval=0s
instrumentation-user=
internet-detection-timeout-ms=3000
last-started-version=v1.24.8
letsencrypt-email=
mailpit-http-port=8025
mailpit-https-port=8026
mkcert-caroot=/mnt/c/Users/andreas/AppData/Local/mkcert
no-bind-mounts=false
omit-containers=[]
performance-mode=none
project-tld=ddev.site
remote-config-update-interval=0
remote-config-url=https://raw.githubusercontent.com/ddev/remote-config/main/remote-config.jsonc
required-docker-compose-version=v2.39.3
router-bind-all-interfaces=false
router-http-port=80
router-https-port=443
simple-formatting=false
sponsorship-data-url=https://ddev.com/s/sponsorship-data.json
table-style=default
traefik-monitor-port=10999
use-docker-compose-from-path=false
use-hardened-images=false
use-letsencrypt=false
wsl2-no-windows-hosts-mgt=false
xdebug-ide-location=
xhgui-http-port=
xhgui-https-port=
xhprof-mode=


======== DOCKER provider info ========
docker client location: lrwxrwxrwx 1 root root 48 Sep 26 07:30 /usr/bin/docker -> /mnt/wsl/docker-desktop/cli-tools/usr/bin/docker

docker client alternate locations:
/usr/bin/docker
/bin/docker
/Docker/host/bin/docker

Docker provider: docker-desktop


======== docker version ========
Client:
 Version:           28.4.0
 API version:       1.51
 Go version:        go1.24.7
 Git commit:        d8eb465
 Built:             Wed Sep  3 20:56:28 2025
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Desktop 4.46.0 (204649)
 Engine:
  Version:          28.4.0
  API version:      1.51 (minimum version 1.24)
  Go version:       go1.24.7
  Git commit:       249d679
  Built:            Wed Sep  3 20:57:37 2025
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.27
  GitCommit:        05044ec0a9a75232cad458027ca83437aae3f4da
 runc:
  Version:          1.2.5
  GitCommit:        v1.2.5-0-g59923ef
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0


======== docker context ls ========
NAME            DESCRIPTION                               DOCKER ENDPOINT                             ERROR
default *       Current DOCKER_HOST based configuration   unix:///var/run/docker.sock
desktop-linux   Docker Desktop                            npipe:////./pipe/dockerDesktopLinuxEngine

DOCKER_HOST=notset
DOCKER_CONTEXT=notset
DOCKER_DEFAULT_PLATFORM=notset


======== ddev debug dockercheck ========
Docker platform: docker-desktop
Using Docker context: default
Using Docker host: unix:///var/run/docker.sock
docker-compose: v2.39.3
Docker version: 28.4.0
Docker API version: 1.51
Able to run simple container that mounts a volume.
Able to use internet inside container.

Docker disk space:
Filesystem                Size      Used Available Use% Mounted on
overlay                1006.9G     37.2G    918.4G   4% /


======== Existing docker containers ========
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES


======== docker system df ========
TYPE            TOTAL     ACTIVE    SIZE      RECLAIMABLE
Images          12        0         3.801GB   3.801GB (100%)
Containers      0         0         0B        0B
Local Volumes   55        0         21.29GB   21.29GB (100%)
Build Cache     57        0         3.104kB   3.104kB

  Tips:
  1. Periodically check your Docker filesystem usage with 'docker system df'
  2. Use 'docker builder prune' to remove unused Docker build cache (it doesn't remove your data)
  3. To remove all containers and images (it doesn't remove your data):
    ```
    ddev poweroff
    docker rm -f $(docker ps -aq) || true
    docker rmi -f $(docker images -q)
    ```
    (DDEV images will be downloaded again on 'ddev start')


======== mkcert information ========
/home/linuxbrew/.linuxbrew/bin/mkcert
v1.4.4
CAROOT=/mnt/c/Users/andreas/AppData/Local/mkcert WSLENV=WT_SESSION:WT_PROFILE_ID:CAROOT/up:WT_SESSION:WT_PROFILE_ID: JAVA_HOME=
/mnt/c/Users/andreas/AppData/Local/mkcert
total 8
-r-xr-xr-x 1 andreas andreas 2484 Feb 20  2025 rootCA-key.pem
-rwxrwxrwx 1 andreas andreas 1740 Feb 20  2025 rootCA.pem


======== ping attempt on ddev.site ========
PING dkdkd.ddev.site (127.0.0.1) 56(84) bytes of data.
64 bytes from localhost (127.0.0.1): icmp_seq=1 ttl=64 time=0.014 ms

--- dkdkd.ddev.site ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.014/0.014/0.014/0.000 ms


======== curl information ========
/usr/bin/curl
/bin/curl
curl 8.5.0 (x86_64-pc-linux-gnu) libcurl/8.5.0 OpenSSL/3.0.13 zlib/1.3 brotli/1.1.0 zstd/1.5.5 libidn2/2.3.7 libpsl/0.21.2 (+libidn2/2.3.7) libssh/0.10.6/openssl/zlib nghttp2/1.59.0 librtmp/2.3 OpenLDAP/2.6.7
Release-Date: 2023-12-06, security patched: 8.5.0-2ubuntu10.6
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM PSL SPNEGO SSL threadsafe TLS-SRP UnixSockets zstd


======== ddev debug rebuild ========
Rebuilding project images without Docker cache...
Executing `/home/andreas/.ddev/bin/docker-compose -f /home/andreas/projects/tryddevproject-14541/.ddev/.ddev-docker-compose-full.yaml --progress plain build web --no-cache`
#1 [internal] load local bake definitions
#1 reading from stdin 885B done
#1 DONE 0.0s

#2 [internal] load build definition from Dockerfile
#2 transferring dockerfile: 1.53kB done
#2 DONE 0.0s

#3 [internal] load metadata for docker.io/ddev/ddev-webserver:v1.24.8
#3 DONE 0.0s

#4 [internal] load .dockerignore
#4 transferring context: 2B done
#4 DONE 0.0s

#5 [1/9] FROM docker.io/ddev/ddev-webserver:v1.24.8
#5 CACHED

#6 [2/9] RUN getent group tty || groupadd tty
#6 0.251 tty:x:5:
#6 DONE 0.3s

#7 [3/9] RUN (groupadd --gid 1000 "andreas" || groupadd "andreas" || true) && (useradd -G tty -l -m -s "/bin/bash" --gid "andreas" --comment '' --uid 1000 "andreas" || useradd -G tty -l -m -s "/bin/bash" --gid "andreas" --comment '' "andreas" || useradd  -G tty -l -m -s "/bin/bash" --gid "1000" --comment '' "andreas" || useradd -G tty -l -m -s "/bin/bash" --comment '' andreas )
#7 DONE 0.5s

#8 [4/9] RUN mkdir -p /home/andreas && chown andreas /home/andreas && chmod 600 /home/andreas/.pgpass
#8 DONE 0.4s

#9 [5/9] RUN export XDEBUG_MODE=off; composer self-update --stable || composer self-update --stable || true; composer self-update --2 || log-stderr.sh composer self-update --2 || true
#9 0.532 Storing "stable" as default update channel for the next self-update run.
#9 0.765 Upgrading to version 2.8.12 (stable channel).
#9 0.812
#9 1.149 Use composer self-update --rollback to return to version 2.8.11
#9 1.385 You are already using the latest available Composer version 2.8.12 (2.x channel).
#9 DONE 1.4s

#10 [6/9] RUN timeout 30 apt-get update || true
#10 0.485 Get:1 http://deb.debian.org/debian bookworm InRelease [151 kB]
#10 0.596 Get:2 http://deb.debian.org/debian bookworm-updates InRelease [55.4 kB]
#10 0.634 Get:3 http://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB]
#10 0.677 Get:4 http://deb.debian.org/debian bookworm/main amd64 Packages [8791 kB]
#10 1.747 Get:5 http://deb.debian.org/debian bookworm-updates/main amd64 Packages [6924 B]
#10 1.782 Get:6 http://deb.debian.org/debian-security bookworm-security/main amd64 Packages [279 kB]
#10 10.51 Get:7 http://nginx.org/packages/debian bookworm InRelease [3293 B]
#10 10.55 Get:9 https://dl.cloudsmith.io/public/platformsh/cli/deb/debian bookworm InRelease [10.2 kB]
#10 10.55 Get:10 https://packages.sury.org/php bookworm InRelease [7551 B]
#10 10.56 Get:11 https://apt.postgresql.org/pub/repos/apt bookworm-pgdg InRelease [107 kB]
#10 10.58 Get:12 http://nginx.org/packages/debian bookworm/nginx amd64 Packages [21.7 kB]
#10 10.59 Get:13 https://dl.cloudsmith.io/public/platformsh/upsun-cli/deb/debian bookworm InRelease [10.2 kB]
#10 10.63 Get:14 https://dl.cloudsmith.io/public/symfony/stable/deb/debian bookworm InRelease [11.0 kB]
#10 10.64 Get:15 https://packages.sury.org/php bookworm/main amd64 Packages [258 kB]
#10 10.71 Get:16 https://apt.postgresql.org/pub/repos/apt bookworm-pgdg/main amd64 Packages [398 kB]
#10 10.83 Get:17 https://dl.cloudsmith.io/public/platformsh/cli/deb/debian bookworm/main amd64 Packages [5355 B]
#10 10.84 Get:8 https://dlm.mariadb.com/repo/mariadb-server/10.11/repo/debian bookworm InRelease [4628 B]
#10 10.95 Get:18 https://dl.cloudsmith.io/public/platformsh/upsun-cli/deb/debian bookworm/main amd64 Packages [4209 B]
#10 11.04 Get:19 https://dl.cloudsmith.io/public/symfony/stable/deb/debian bookworm/main amd64 Packages [9381 B]
#10 11.15 Get:20 http://packages.blackfire.io/debian any InRelease [29.2 kB]
#10 11.46 Get:21 https://dlm.mariadb.com/repo/mariadb-server/10.11/repo/debian bookworm/main arm64 Packages [34.4 kB]
#10 11.89 Get:22 https://dlm.mariadb.com/repo/mariadb-server/10.11/repo/debian bookworm/main amd64 Packages [40.0 kB]
#10 11.92 Get:23 http://packages.blackfire.io/debian any/main amd64 Packages [34.9 kB]
#10 12.00 Fetched 10.3 MB in 12s (887 kB/s)
#10 12.00 Reading package lists...
#10 DONE 12.4s

#11 [7/9] RUN curl --connect-timeout 10 --max-time 20 --fail -I https://www.google.com || true
#11 0.526   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
#11 0.526                                  Dload  Upload   Total   Spent    Left  Speed
#11 0.526
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
#11 0.642 HTTP/2 200
#11 0.642 content-type: text/html; charset=ISO-8859-1
#11 0.642 content-security-policy-report-only: object-src 'none';base-uri 'self';script-src 'nonce-WRRz4Hdj1bZZijECrjMcGQ' 'strict-dynamic' 'report-sample' 'unsafe-eval' 'unsafe-inline' https: http:;report-uri https://csp.withgoogle.com/csp/gws/other-hp
#11 0.642 accept-ch: Sec-CH-Prefers-Color-Scheme
#11 0.642 p3p: CP="This is not a P3P policy! See g.co/p3phelp for more info."
#11 0.642 date: Fri, 26 Sep 2025 05:51:49 GMT
#11 0.642 server: gws
#11 0.642 x-xss-protection: 0
#11 0.642 x-frame-options: SAMEORIGIN
#11 0.642 expires: Fri, 26 Sep 2025 05:51:49 GMT
#11 0.642 cache-control: private
#11 0.642 set-cookie: AEC=AaJma5scinyROYSFBoN4DnM_dfwZpyQiG2QrzIaQvPiT6eu8SgiVAwrHg5s; expires=Wed, 25-Mar-2026 05:51:49 GMT; path=/; domain=.google.com; Secure; HttpOnly; SameSite=lax
#11 0.642 set-cookie: __Secure-ENID=28.SE=mmnj80HBKY-5wI75K43RePkBf3CLHrsGn5dFDZQCFPaIktlTpNU-mMPqSeBTQwnB0R93AfqDuwPIpL2BTDbhVM6fjvJU7FgxyYm1b4U_xQ3Xtr_0BeQabYduzgT7w2kSn6qhfDo8DUcvMSaxWCIiQq4sLa_Tjahom63Tn7gQZ2dQgMOj5NoUATFjOHr6J2sVXmFLhuVvo3wZtj8zElZcFfvQag6rnAxOwAJUpspzsaZi0wey4Be2WlNzWM6R; expires=Mon, 26-Oct-2026 22:10:07 GMT; path=/; domain=.google.com; Secure; HttpOnly; SameSite=lax
#11 0.642 alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
#11 0.642
#11 DONE 0.7s

#12 [8/9] RUN chmod 777 /run/php /var/log
#12 DONE 0.5s

#13 [9/9] RUN mkdir -p /tmp/xhprof && chmod -R ugo+w /etc/php /var/lib/php /tmp/xhprof
#13 DONE 1.9s

#14 exporting to image
#14 exporting layers
#14 exporting layers 0.3s done
#14 writing image sha256:d0039c3fdab13b113a91e6b067421341ea0ec142746387bc3eed70294827f520 done
#14 naming to docker.io/ddev/ddev-webserver:v1.24.8-tryddevproject-14541-built 0.0s done
#14 DONE 0.3s

#15 resolving provenance for metadata file
#15 DONE 0.0s
 ddev/ddev-webserver:v1.24.8-tryddevproject-14541-built  Built
Rebuilt web service cache for tryddevproject-14541 in 19s
Network ddev_default created
 ddev-ddev-dbserver-mariadb-10.11-v1.24.8 Pulling
 60d98d907669 Already exists
 99d06c66f898 Pulling fs layer
 1427991e2f34 Pulling fs layer
 d37470673b78 Pulling fs layer
 7197601ade72 Pulling fs layer
 1cb464ad4e0a Pulling fs layer
 b0c286c50b3b Pulling fs layer
 19683e685d48 Pulling fs layer
 4f4fb700ef54 Pulling fs layer
 3d4498f9e4d9 Pulling fs layer
 4c0f717cfc29 Pulling fs layer
 910245695c76 Pulling fs layer
 2d8228c49a4f Pulling fs layer
 19683e685d48 Waiting
 4f4fb700ef54 Waiting
 80fe7bad8e82 Pulling fs layer
 56a2dddaaf8e Pulling fs layer
 776aaf8119f0 Pulling fs layer
 a10f83556e33 Pulling fs layer
 7e6ed3485fef Pulling fs layer
 f9fabdd6817f Pulling fs layer
 c9d31fd47db8 Pulling fs layer
 29a08a29ebbc Pulling fs layer
 7dcfbfec30a8 Pulling fs layer
 3d4498f9e4d9 Waiting
 03b865d61818 Pulling fs layer
 e623a33dbe00 Pulling fs layer
 31abbfa3c242 Pulling fs layer
 642a81eddd3b Pulling fs layer
 2ef81f643aa6 Pulling fs layer
 776aaf8119f0 Waiting
 a10f83556e33 Waiting
 7e6ed3485fef Waiting
 4c0f717cfc29 Waiting
 910245695c76 Waiting
 2d8228c49a4f Waiting
 80fe7bad8e82 Waiting
 56a2dddaaf8e Waiting
 f9fabdd6817f Waiting
 c9d31fd47db8 Waiting
 e623a33dbe00 Waiting
 7197601ade72 Waiting
 31abbfa3c242 Waiting
 1cb464ad4e0a Waiting
 642a81eddd3b Waiting
 2ef81f643aa6 Waiting
 29a08a29ebbc Waiting
 b0c286c50b3b Waiting
 7dcfbfec30a8 Waiting
 03b865d61818 Waiting
 d37470673b78 Downloading [==================================================>]     116B/116B
 d37470673b78 Download complete
 99d06c66f898 Downloading [===========================>                       ]     933B/1.721kB
 99d06c66f898 Downloading [==================================================>]  1.721kB/1.721kB
 99d06c66f898 Download complete
 99d06c66f898 Extracting [==================================================>]  1.721kB/1.721kB
 99d06c66f898 Extracting [==================================================>]  1.721kB/1.721kB
 1427991e2f34 Downloading [>                                                  ]  57.34kB/5.66MB
 99d06c66f898 Pull complete
 1427991e2f34 Downloading [======>                                            ]  696.3kB/5.66MB
 1427991e2f34 Downloading [==============>                                    ]  1.678MB/5.66MB
 1427991e2f34 Downloading [=============================>                     ]  3.308MB/5.66MB
 1427991e2f34 Downloading [======================================>            ]  4.357MB/5.66MB
 1427991e2f34 Downloading [================================================>  ]  5.472MB/5.66MB
 1427991e2f34 Downloading [==================================================>]   5.66MB/5.66MB
 1427991e2f34 Verifying Checksum
 1427991e2f34 Download complete
 1427991e2f34 Extracting [>                                                  ]  65.54kB/5.66MB
 7197601ade72 Download complete
 1427991e2f34 Extracting [======================================>            ]  4.391MB/5.66MB
 1cb464ad4e0a Downloading [>                                                  ]  532.5kB/70.16MB
 1427991e2f34 Extracting [=========================================>         ]  4.653MB/5.66MB
 1cb464ad4e0a Downloading [=>                                                 ]  1.603MB/70.16MB
 1427991e2f34 Extracting [==========================================>        ]  4.784MB/5.66MB
 1cb464ad4e0a Downloading [==>                                                ]  3.213MB/70.16MB
 1427991e2f34 Extracting [============================================>      ]  4.981MB/5.66MB
 1427991e2f34 Extracting [==================================================>]   5.66MB/5.66MB
 1cb464ad4e0a Downloading [===>                                               ]  4.835MB/70.16MB
 1427991e2f34 Pull complete
 d37470673b78 Extracting [==================================================>]     116B/116B
 d37470673b78 Extracting [==================================================>]     116B/116B
 d37470673b78 Pull complete
 7197601ade72 Extracting [==================================================>]     332B/332B
 7197601ade72 Extracting [==================================================>]     332B/332B
 b0c286c50b3b Downloading [===========>                                       ]     934B/4.021kB
 b0c286c50b3b Downloading [==================================================>]  4.021kB/4.021kB
 b0c286c50b3b Verifying Checksum
 b0c286c50b3b Download complete
 19683e685d48 Downloading [=====>                                             ]     934B/8.369kB
 19683e685d48 Downloading [==================================================>]  8.369kB/8.369kB
 19683e685d48 Verifying Checksum
 19683e685d48 Download complete
 7197601ade72 Pull complete
 1cb464ad4e0a Downloading [====>                                              ]  6.446MB/70.16MB
 1cb464ad4e0a Downloading [=====>                                             ]  8.062MB/70.16MB
 1cb464ad4e0a Downloading [======>                                            ]  9.121MB/70.16MB
 1cb464ad4e0a Downloading [=======>                                           ]  10.18MB/70.16MB
 1cb464ad4e0a Downloading [========>                                          ]  11.26MB/70.16MB
 4f4fb700ef54 Downloading [==================================================>]      32B/32B
 4f4fb700ef54 Verifying Checksum
 4f4fb700ef54 Download complete
 1cb464ad4e0a Downloading [=========>                                         ]   13.4MB/70.16MB
 3d4498f9e4d9 Downloading [==================================================>]     184B/184B
 3d4498f9e4d9 Verifying Checksum
 3d4498f9e4d9 Download complete
 1cb464ad4e0a Downloading [==========>                                        ]  15.01MB/70.16MB
 1cb464ad4e0a Downloading [===========>                                       ]  16.62MB/70.16MB
 1cb464ad4e0a Downloading [============>                                      ]   17.7MB/70.16MB
 4c0f717cfc29 Downloading [==================================================>]     179B/179B
 4c0f717cfc29 Verifying Checksum
 4c0f717cfc29 Download complete
 1cb464ad4e0a Downloading [==============>                                    ]  19.85MB/70.16MB
 1cb464ad4e0a Downloading [===============>                                   ]  21.44MB/70.16MB
 1cb464ad4e0a Downloading [================>                                  ]  23.04MB/70.16MB
 1cb464ad4e0a Downloading [=================>                                 ]  24.11MB/70.16MB
 910245695c76 Downloading [>                                                  ]  532.5kB/60.5MB
 1cb464ad4e0a Downloading [==================>                                ]  25.73MB/70.16MB
 2d8228c49a4f Downloading [============================>                      ]     934B/1.625kB
 2d8228c49a4f Downloading [==================================================>]  1.625kB/1.625kB
 2d8228c49a4f Verifying Checksum
 2d8228c49a4f Download complete
 1cb464ad4e0a Downloading [===================>                               ]  27.88MB/70.16MB
 910245695c76 Downloading [>                                                  ]  1.071MB/60.5MB
 1cb464ad4e0a Downloading [====================>                              ]  28.95MB/70.16MB
 1cb464ad4e0a Downloading [=====================>                             ]  30.03MB/70.16MB
 910245695c76 Downloading [=>                                                 ]  1.607MB/60.5MB
 80fe7bad8e82 Download complete
 1cb464ad4e0a Downloading [======================>                            ]   31.1MB/70.16MB
 1cb464ad4e0a Downloading [======================>                            ]  31.64MB/70.16MB
 910245695c76 Downloading [=>                                                 ]  2.135MB/60.5MB
 1cb464ad4e0a Downloading [=======================>                           ]  33.25MB/70.16MB
 910245695c76 Downloading [==>                                                ]  2.676MB/60.5MB
 1cb464ad4e0a Downloading [========================>                          ]  34.32MB/70.16MB
 1cb464ad4e0a Downloading [=========================>                         ]   35.4MB/70.16MB
 910245695c76 Downloading [==>                                                ]  3.206MB/60.5MB
 1cb464ad4e0a Downloading [=========================>                         ]  36.46MB/70.16MB
 910245695c76 Downloading [===>                                               ]  3.737MB/60.5MB
 56a2dddaaf8e Downloading [==================================================>]     137B/137B
 56a2dddaaf8e Verifying Checksum
 56a2dddaaf8e Download complete
 1cb464ad4e0a Downloading [==========================>                        ]  37.54MB/70.16MB
 910245695c76 Downloading [===>                                               ]  4.278MB/60.5MB
 1cb464ad4e0a Downloading [===========================>                       ]  38.62MB/70.16MB
 910245695c76 Downloading [===>                                               ]  4.818MB/60.5MB
 1cb464ad4e0a Downloading [============================>                      ]  40.23MB/70.16MB
 910245695c76 Downloading [====>                                              ]  5.351MB/60.5MB
 1cb464ad4e0a Downloading [=============================>                     ]   41.3MB/70.16MB
 1cb464ad4e0a Downloading [==============================>                    ]  42.37MB/70.16MB
 776aaf8119f0 Downloading [=====>                                             ]     934B/8.814kB
 910245695c76 Downloading [====>                                              ]  5.891MB/60.5MB
 776aaf8119f0 Downloading [==================================================>]  8.814kB/8.814kB
 776aaf8119f0 Verifying Checksum
 776aaf8119f0 Download complete
 1cb464ad4e0a Downloading [==============================>                    ]  42.92MB/70.16MB
 910245695c76 Downloading [=====>                                             ]  6.954MB/60.5MB
 1cb464ad4e0a Downloading [===============================>                   ]  44.54MB/70.16MB
 910245695c76 Downloading [======>                                            ]  7.485MB/60.5MB
 1cb464ad4e0a Downloading [================================>                  ]  45.61MB/70.16MB
 910245695c76 Downloading [======>                                            ]  8.022MB/60.5MB
 1cb464ad4e0a Downloading [================================>                  ]  46.15MB/70.16MB
 a10f83556e33 Downloading [>                                                  ]     933B/48.61kB
 1cb464ad4e0a Downloading [=================================>                 ]  47.21MB/70.16MB
 910245695c76 Downloading [=======>                                           ]   9.09MB/60.5MB
 1cb464ad4e0a Downloading [==================================>                ]  48.81MB/70.16MB
 a10f83556e33 Downloading [==========================================>        ]  41.12kB/48.61kB
 a10f83556e33 Downloading [==================================================>]  48.61kB/48.61kB
 a10f83556e33 Verifying Checksum
 a10f83556e33 Download complete
 910245695c76 Downloading [========>                                          ]  10.17MB/60.5MB
 1cb464ad4e0a Downloading [===================================>               ]  49.88MB/70.16MB
 910245695c76 Downloading [========>                                          ]  10.71MB/60.5MB
 1cb464ad4e0a Downloading [====================================>              ]  50.95MB/70.16MB
 910245695c76 Downloading [=========>                                         ]  11.25MB/60.5MB
 1cb464ad4e0a Downloading [=====================================>             ]  52.01MB/70.16MB
 910245695c76 Downloading [==========>                                        ]  12.32MB/60.5MB
 1cb464ad4e0a Downloading [=====================================>             ]  53.09MB/70.16MB
 910245695c76 Downloading [==========>                                        ]  12.86MB/60.5MB
 7e6ed3485fef Downloading [==================================================>]     155B/155B
 7e6ed3485fef Download complete
 1cb464ad4e0a Downloading [======================================>            ]  54.16MB/70.16MB
 910245695c76 Downloading [===========>                                       ]  13.39MB/60.5MB
 910245695c76 Downloading [===========>                                       ]  14.44MB/60.5MB
 1cb464ad4e0a Downloading [=======================================>           ]  55.22MB/70.16MB
 910245695c76 Downloading [============>                                      ]  14.98MB/60.5MB
 1cb464ad4e0a Downloading [=======================================>           ]  55.75MB/70.16MB
 1cb464ad4e0a Downloading [========================================>          ]  56.83MB/70.16MB
 910245695c76 Downloading [=============>                                     ]  16.07MB/60.5MB
 1cb464ad4e0a Downloading [=========================================>         ]   57.9MB/70.16MB
 910245695c76 Downloading [=============>                                     ]  16.61MB/60.5MB
 910245695c76 Downloading [==============>                                    ]  17.67MB/60.5MB
 1cb464ad4e0a Downloading [==========================================>        ]  58.98MB/70.16MB
 f9fabdd6817f Downloading [>                                                  ]  95.14kB/9.439MB
 1cb464ad4e0a Downloading [==========================================>        ]  59.51MB/70.16MB
 910245695c76 Downloading [===============>                                   ]  18.74MB/60.5MB
 1cb464ad4e0a Downloading [==========================================>        ]  60.05MB/70.16MB
 f9fabdd6817f Downloading [==>                                                ]  399.8kB/9.439MB
 910245695c76 Downloading [===============>                                   ]  19.27MB/60.5MB
 1cb464ad4e0a Downloading [===========================================>       ]  60.58MB/70.16MB
 910245695c76 Downloading [================>                                  ]   19.8MB/60.5MB
 f9fabdd6817f Downloading [===>                                               ]  702.9kB/9.439MB
 1cb464ad4e0a Downloading [===========================================>       ]  61.13MB/70.16MB
 f9fabdd6817f Downloading [=====>                                             ]  997.8kB/9.439MB
 910245695c76 Downloading [=================>                                 ]  20.88MB/60.5MB
 1cb464ad4e0a Downloading [============================================>      ]  62.19MB/70.16MB
 f9fabdd6817f Downloading [======>                                            ]  1.293MB/9.439MB
 910245695c76 Downloading [==================>                                ]  21.94MB/60.5MB
 1cb464ad4e0a Downloading [============================================>      ]  62.73MB/70.16MB
 f9fabdd6817f Downloading [========>                                          ]  1.588MB/9.439MB
 910245695c76 Downloading [===================>                               ]  23.02MB/60.5MB
 f9fabdd6817f Downloading [==========>                                        ]  1.989MB/9.439MB
 910245695c76 Downloading [===================>                               ]   24.1MB/60.5MB
 1cb464ad4e0a Downloading [=============================================>     ]  63.82MB/70.16MB
 f9fabdd6817f Downloading [============>                                      ]  2.382MB/9.439MB
 1cb464ad4e0a Downloading [=============================================>     ]  64.36MB/70.16MB
 910245695c76 Downloading [====================>                              ]  25.18MB/60.5MB
 f9fabdd6817f Downloading [=============>                                     ]  2.481MB/9.439MB
 1cb464ad4e0a Downloading [==============================================>    ]  64.89MB/70.16MB
 f9fabdd6817f Downloading [===============>                                   ]  2.874MB/9.439MB
 910245695c76 Downloading [=====================>                             ]  26.25MB/60.5MB
 1cb464ad4e0a Downloading [==============================================>    ]  65.42MB/70.16MB
 f9fabdd6817f Downloading [=================>                                 ]  3.267MB/9.439MB
 f9fabdd6817f Downloading [==================>                                ]  3.569MB/9.439MB
 910245695c76 Downloading [======================>                            ]  27.33MB/60.5MB
 1cb464ad4e0a Downloading [===============================================>   ]  65.96MB/70.16MB
 f9fabdd6817f Downloading [====================>                              ]   3.86MB/9.439MB
 1cb464ad4e0a Downloading [===============================================>   ]   66.5MB/70.16MB
 910245695c76 Downloading [=======================>                           ]   28.4MB/60.5MB
 f9fabdd6817f Downloading [=====================>                             ]  4.057MB/9.439MB
 910245695c76 Downloading [=======================>                           ]  28.93MB/60.5MB
 1cb464ad4e0a Downloading [===============================================>   ]  67.04MB/70.16MB
 f9fabdd6817f Downloading [=======================>                           ]   4.45MB/9.439MB
 1cb464ad4e0a Downloading [================================================>  ]  67.56MB/70.16MB
 910245695c76 Downloading [========================>                          ]  30.01MB/60.5MB
 f9fabdd6817f Downloading [=========================>                         ]  4.843MB/9.439MB
 1cb464ad4e0a Downloading [================================================>  ]  68.09MB/70.16MB
 910245695c76 Downloading [=========================>                         ]  31.08MB/60.5MB
 f9fabdd6817f Downloading [===========================>                       ]  5.138MB/9.439MB
 910245695c76 Downloading [==========================>                        ]  31.61MB/60.5MB
 1cb464ad4e0a Downloading [================================================>  ]  68.62MB/70.16MB
 f9fabdd6817f Downloading [=============================>                     ]  5.537MB/9.439MB
 f9fabdd6817f Downloading [==============================>                    ]  5.733MB/9.439MB
 910245695c76 Downloading [===========================>                       ]  32.68MB/60.5MB
 1cb464ad4e0a Downloading [=================================================> ]  69.15MB/70.16MB
 f9fabdd6817f Downloading [================================>                  ]  6.127MB/9.439MB
 910245695c76 Downloading [===========================>                       ]  33.75MB/60.5MB
 1cb464ad4e0a Downloading [=================================================> ]  69.68MB/70.16MB
 910245695c76 Downloading [============================>                      ]  34.82MB/60.5MB
 f9fabdd6817f Downloading [==================================>                ]   6.52MB/9.439MB
 f9fabdd6817f Downloading [=====================================>             ]   7.11MB/9.439MB
 910245695c76 Downloading [=============================>                     ]  35.88MB/60.5MB
 1cb464ad4e0a Verifying Checksum
 1cb464ad4e0a Download complete
 1cb464ad4e0a Extracting [>                                                  ]  557.1kB/70.16MB
 f9fabdd6817f Downloading [========================================>          ]  7.601MB/9.439MB
 910245695c76 Downloading [==============================>                    ]  36.95MB/60.5MB
 1cb464ad4e0a Extracting [===>                                               ]  5.571MB/70.16MB
 910245695c76 Downloading [===============================>                   ]  38.01MB/60.5MB
 f9fabdd6817f Downloading [==========================================>        ]  7.994MB/9.439MB
 1cb464ad4e0a Extracting [=========>                                         ]  12.81MB/70.16MB
 910245695c76 Downloading [===============================>                   ]  38.53MB/60.5MB
 f9fabdd6817f Downloading [============================================>      ]  8.486MB/9.439MB
 1cb464ad4e0a Extracting [=============>                                     ]   19.5MB/70.16MB
 f9fabdd6817f Downloading [==============================================>    ]  8.781MB/9.439MB
 910245695c76 Downloading [================================>                  ]  39.61MB/60.5MB
 1cb464ad4e0a Extracting [=================>                                 ]  24.51MB/70.16MB
 1cb464ad4e0a Extracting [=====================>                             ]  29.52MB/70.16MB
 f9fabdd6817f Downloading [=================================================> ]  9.371MB/9.439MB
 910245695c76 Downloading [=================================>                 ]  40.68MB/60.5MB
 f9fabdd6817f Verifying Checksum
 f9fabdd6817f Download complete
 c9d31fd47db8 Downloading [==================================================>]     688B/688B
 c9d31fd47db8 Verifying Checksum
 c9d31fd47db8 Download complete
 1cb464ad4e0a Extracting [============================>                      ]  39.55MB/70.16MB
 910245695c76 Downloading [==================================>                ]  41.75MB/60.5MB
 1cb464ad4e0a Extracting [===============================>                   ]  44.56MB/70.16MB
 910245695c76 Downloading [===================================>               ]  43.35MB/60.5MB
 1cb464ad4e0a Extracting [===================================>               ]  49.58MB/70.16MB
 1cb464ad4e0a Extracting [=====================================>             ]  52.92MB/70.16MB
 910245695c76 Downloading [=====================================>             ]   45.5MB/60.5MB
 1cb464ad4e0a Extracting [=======================================>           ]  55.71MB/70.16MB
 29a08a29ebbc Downloading [==================================================>]      93B/93B
 29a08a29ebbc Verifying Checksum
 29a08a29ebbc Download complete
 910245695c76 Downloading [======================================>            ]  46.03MB/60.5MB
 7dcfbfec30a8 Downloading [==================================================>]     440B/440B
 7dcfbfec30a8 Verifying Checksum
 7dcfbfec30a8 Download complete
 1cb464ad4e0a Extracting [=============================================>     ]   63.5MB/70.16MB
 1cb464ad4e0a Extracting [==============================================>    ]  65.73MB/70.16MB
 1cb464ad4e0a Extracting [================================================>  ]   67.4MB/70.16MB
 910245695c76 Downloading [======================================>            ]  46.56MB/60.5MB
 1cb464ad4e0a Extracting [=================================================> ]  69.63MB/70.16MB
 1cb464ad4e0a Extracting [==================================================>]  70.16MB/70.16MB
 03b865d61818 Downloading [>                                                  ]  43.74kB/4.265MB
 1cb464ad4e0a Extracting [==================================================>]  70.16MB/70.16MB
 e623a33dbe00 Downloading [================================>                  ]     934B/1.443kB
 e623a33dbe00 Downloading [==================================================>]  1.443kB/1.443kB
 e623a33dbe00 Verifying Checksum
 e623a33dbe00 Download complete
 1cb464ad4e0a Pull complete
 b0c286c50b3b Extracting [==================================================>]  4.021kB/4.021kB
 b0c286c50b3b Extracting [==================================================>]  4.021kB/4.021kB
 03b865d61818 Downloading [=======>                                           ]  616.6kB/4.265MB
 b0c286c50b3b Pull complete
 19683e685d48 Extracting [==================================================>]  8.369kB/8.369kB
 19683e685d48 Extracting [==================================================>]  8.369kB/8.369kB
 19683e685d48 Pull complete
 4f4fb700ef54 Extracting [==================================================>]      32B/32B
 4f4fb700ef54 Extracting [==================================================>]      32B/32B
 4f4fb700ef54 Pull complete
 03b865d61818 Downloading [======================>                            ]  1.934MB/4.265MB
 03b865d61818 Downloading [============================================>      ]  3.758MB/4.265MB
 03b865d61818 Verifying Checksum
 03b865d61818 Download complete
 910245695c76 Downloading [======================================>            ]   47.1MB/60.5MB
 31abbfa3c242 Downloading [==================================================>]     122B/122B
 31abbfa3c242 Verifying Checksum
 31abbfa3c242 Download complete
 910245695c76 Downloading [=======================================>           ]  47.64MB/60.5MB
 3d4498f9e4d9 Extracting [==================================================>]     184B/184B
 3d4498f9e4d9 Extracting [==================================================>]     184B/184B
 642a81eddd3b Downloading [===================>                               ]     934B/2.382kB
 642a81eddd3b Downloading [==================================================>]  2.382kB/2.382kB
 642a81eddd3b Download complete
 3d4498f9e4d9 Pull complete
 4c0f717cfc29 Extracting [==================================================>]     179B/179B
 4c0f717cfc29 Extracting [==================================================>]     179B/179B
 4c0f717cfc29 Pull complete
 2ef81f643aa6 Downloading [==================================================>]     124B/124B
 2ef81f643aa6 Verifying Checksum
 2ef81f643aa6 Download complete
 910245695c76 Downloading [=======================================>           ]  48.17MB/60.5MB
 910245695c76 Downloading [========================================>          ]   48.7MB/60.5MB
 910245695c76 Downloading [========================================>          ]  49.23MB/60.5MB
 910245695c76 Downloading [=========================================>         ]  49.77MB/60.5MB
 910245695c76 Downloading [=========================================>         ]  50.31MB/60.5MB
 910245695c76 Downloading [==========================================>        ]  50.84MB/60.5MB
 910245695c76 Downloading [==========================================>        ]  51.37MB/60.5MB
 910245695c76 Downloading [==========================================>        ]  51.91MB/60.5MB
 910245695c76 Downloading [===========================================>       ]  52.44MB/60.5MB
 910245695c76 Downloading [===========================================>       ]  52.98MB/60.5MB
 910245695c76 Downloading [============================================>      ]   53.5MB/60.5MB
 910245695c76 Downloading [============================================>      ]  54.04MB/60.5MB
 910245695c76 Downloading [=============================================>     ]  54.57MB/60.5MB
 910245695c76 Downloading [=============================================>     ]  55.11MB/60.5MB
 910245695c76 Downloading [=============================================>     ]  55.64MB/60.5MB
 910245695c76 Downloading [==============================================>    ]  56.17MB/60.5MB
 910245695c76 Downloading [==============================================>    ]   56.7MB/60.5MB
 910245695c76 Downloading [===============================================>   ]  57.23MB/60.5MB
 910245695c76 Downloading [===============================================>   ]  57.77MB/60.5MB
 910245695c76 Downloading [================================================>  ]  58.31MB/60.5MB
 910245695c76 Downloading [================================================>  ]  58.84MB/60.5MB
 910245695c76 Downloading [=================================================> ]  59.37MB/60.5MB
 910245695c76 Downloading [=================================================> ]   59.9MB/60.5MB
 910245695c76 Downloading [=================================================> ]  60.43MB/60.5MB
 910245695c76 Verifying Checksum
 910245695c76 Download complete
 910245695c76 Extracting [>                                                  ]  557.1kB/60.5MB
 910245695c76 Extracting [=====>                                             ]  7.242MB/60.5MB
 910245695c76 Extracting [======>                                            ]  8.356MB/60.5MB
 910245695c76 Extracting [=========>                                         ]   11.7MB/60.5MB
 910245695c76 Extracting [===============>                                   ]  18.38MB/60.5MB
 910245695c76 Extracting [==========================>                        ]  32.31MB/60.5MB
 910245695c76 Extracting [======================================>            ]  46.79MB/60.5MB
 910245695c76 Extracting [=================================================> ]  60.16MB/60.5MB
 910245695c76 Extracting [==================================================>]   60.5MB/60.5MB
 910245695c76 Pull complete
 2d8228c49a4f Extracting [==================================================>]  1.625kB/1.625kB
 2d8228c49a4f Extracting [==================================================>]  1.625kB/1.625kB
 2d8228c49a4f Pull complete
 80fe7bad8e82 Extracting [==================================================>]     177B/177B
 80fe7bad8e82 Extracting [==================================================>]     177B/177B
 80fe7bad8e82 Pull complete
 56a2dddaaf8e Extracting [==================================================>]     137B/137B
 56a2dddaaf8e Extracting [==================================================>]     137B/137B
 56a2dddaaf8e Pull complete
 776aaf8119f0 Extracting [==================================================>]  8.814kB/8.814kB
 776aaf8119f0 Extracting [==================================================>]  8.814kB/8.814kB
 776aaf8119f0 Pull complete
 a10f83556e33 Extracting [=================================>                 ]  32.77kB/48.61kB
 a10f83556e33 Extracting [==================================================>]  48.61kB/48.61kB
 a10f83556e33 Pull complete
 7e6ed3485fef Extracting [==================================================>]     155B/155B
 7e6ed3485fef Extracting [==================================================>]     155B/155B
 7e6ed3485fef Pull complete
 f9fabdd6817f Extracting [>                                                  ]   98.3kB/9.439MB
 f9fabdd6817f Extracting [========================================>          ]  7.569MB/9.439MB
 f9fabdd6817f Extracting [==================================================>]  9.439MB/9.439MB
 f9fabdd6817f Pull complete
 c9d31fd47db8 Extracting [==================================================>]     688B/688B
 c9d31fd47db8 Extracting [==================================================>]     688B/688B
 c9d31fd47db8 Pull complete
 29a08a29ebbc Extracting [==================================================>]      93B/93B
 29a08a29ebbc Extracting [==================================================>]      93B/93B
 29a08a29ebbc Pull complete
 7dcfbfec30a8 Extracting [==================================================>]     440B/440B
 7dcfbfec30a8 Extracting [==================================================>]     440B/440B
 7dcfbfec30a8 Pull complete
 03b865d61818 Extracting [>                                                  ]  65.54kB/4.265MB
 03b865d61818 Extracting [==================================================>]  4.265MB/4.265MB
 03b865d61818 Pull complete
 e623a33dbe00 Extracting [==================================================>]  1.443kB/1.443kB
 e623a33dbe00 Extracting [==================================================>]  1.443kB/1.443kB
 e623a33dbe00 Pull complete
 31abbfa3c242 Extracting [==================================================>]     122B/122B
 31abbfa3c242 Extracting [==================================================>]     122B/122B
 31abbfa3c242 Pull complete
 642a81eddd3b Extracting [==================================================>]  2.382kB/2.382kB
 642a81eddd3b Extracting [==================================================>]  2.382kB/2.382kB
 642a81eddd3b Pull complete
 2ef81f643aa6 Extracting [==================================================>]     124B/124B
 2ef81f643aa6 Extracting [==================================================>]     124B/124B
 2ef81f643aa6 Pull complete
 ddev-ddev-dbserver-mariadb-10.11-v1.24.8 Pulled
 Container ddev-ssh-agent  Created
 Container ddev-ssh-agent  Started
ssh-agent container is running: If you want to add authentication to the ssh-agent container, run 'ddev auth ssh' to enable your keys.
Using custom web-build configuration:
  - /home/andreas/projects/tryddevproject-14541/.ddev/web-build/Dockerfile.test

Custom configuration is updated on restart.
If you don't see your custom configuration taking effect, run 'ddev restart'.
Building project images.....
Project images built in 3s.
 Network ddev-tryddevproject-14541_default  Created
 Container ddev-tryddevproject-14541-db  Created
 Container ddev-tryddevproject-14541-web  Created
 Container ddev-tryddevproject-14541-web  Started
 Container ddev-tryddevproject-14541-db  Started
Waiting for containers to become ready: [web db]
Starting ddev-router if necessary...
 Container ddev-router  Created
 Container ddev-router  Started
Restarted tryddevproject-14541


======== Project startup ========
2025-09-26T07:52:47.670 Downloading sponsorship data from remote source.
Starting tryddevproject-14541...
2025-09-26T07:52:48.006 GetAvailableRouterPort(): Router is healthy and running
2025-09-26T07:52:48.017 GetAvailableRouterPort(): proposedPort 80 already bound on ddev-router, accepting it
2025-09-26T07:52:48.028 GetAvailableRouterPort(): Router is healthy and running
2025-09-26T07:52:48.038 GetAvailableRouterPort(): proposedPort 443 already bound on ddev-router, accepting it
2025-09-26T07:52:48.049 GetAvailableRouterPort(): Router is healthy and running
2025-09-26T07:52:48.060 GetAvailableRouterPort(): proposedPort 8025 already bound on ddev-router, accepting it
2025-09-26T07:52:48.071 GetAvailableRouterPort(): Router is healthy and running
2025-09-26T07:52:48.081 GetAvailableRouterPort(): proposedPort 8026 already bound on ddev-router, accepting it
2025-09-26T07:52:48.092 GetAvailableRouterPort(): Router is healthy and running
2025-09-26T07:52:48.102 GetAvailableRouterPort(): proposedPort 8143 already bound on ddev-router, accepting it
2025-09-26T07:52:48.113 GetAvailableRouterPort(): Router is healthy and running
2025-09-26T07:52:48.124 GetAvailableRouterPort(): proposedPort 8142 already bound on ddev-router, accepting it
2025-09-26T07:52:48.838 creating docker volume ddev-global-cache
2025-09-26T07:52:48.843 creating docker volume ddev-tryddevproject-14541-snapshots
2025-09-26T07:52:49.678 chowning /mnt/ddev-global-cache and /var/lib/mysql to 1000
2025-09-26T07:52:50.254 done chowning /mnt/ddev-global-cache and /var/lib/mysql to 1000
Using custom web-build configuration:
  - /home/andreas/projects/tryddevproject-14541/.ddev/web-build/Dockerfile.test

Custom configuration is updated on restart.
If you don't see your custom configuration taking effect, run 'ddev restart'.
2025-09-26T07:52:50.293 host.docker.internal='' because IsWSL2 and IsDockerDesktop
2025-09-26T07:52:50.293 Using automatically detected timezone: TZ=Europe/Vienna
Building project images...
2025-09-26T07:52:50.417 Executing docker-compose -f /home/andreas/projects/tryddevproject-14541/.ddev/.ddev-docker-compose-full.yaml build --progress=plain
.
Project images built in 2s.
2025-09-26T07:52:51.923 Removing dangling images for the project ddev-tryddevproject-14541
2025-09-26T07:52:51.930 Executing docker-compose -f /home/andreas/projects/tryddevproject-14541/.ddev/.ddev-docker-compose-full.yaml up -d
 Container ddev-tryddevproject-14541-db  Recreate
 Container ddev-tryddevproject-14541-web  Recreate
 Container ddev-tryddevproject-14541-db  Recreated
 Container ddev-tryddevproject-14541-web  Recreated
 Container ddev-tryddevproject-14541-db  Started
 Container ddev-tryddevproject-14541-web  Started
2025-09-26T07:53:04.643 VIRTUAL_HOST=tryddevproject-14541.ddev.site for web
2025-09-26T07:53:04.643 HTTP_EXPOSE=80:80,8025:8025 for web
2025-09-26T07:53:04.643 HTTPS_EXPOSE=443:80,8026:8025 for web
2025-09-26T07:53:04.643 VIRTUAL_HOST=tryddevproject-14541.ddev.site for xhgui
2025-09-26T07:53:04.643 HTTP_EXPOSE=8143:80 for xhgui
2025-09-26T07:53:04.643 HTTPS_EXPOSE=8142:80 for xhgui
2025-09-26T07:53:04.985 Copied /home/andreas/projects/tryddevproject-14541/.ddev/traefik:CopyIntoVolume_srjonhzcjdkx into /mnt/v/traefik in 45.906172ms
2025-09-26T07:53:05.022 Exec chown -R 1000 /mnt/v/traefik stdout=, stderr=, err=<nil>
2025-09-26T07:53:05.296 Copied Traefik certs in /home/andreas/projects/tryddevproject-14541/.ddev/traefik/certs to ddev-global-cache/traefik
2025-09-26T07:53:05.296 Running /start.sh in ddev-webserver
Waiting for containers to become ready: [web db]
2025-09-26T07:53:08.391 Copied /home/andreas/.ddev/commands:CopyIntoVolume_xfwurifuqjpc into /mnt/v/global-commands in 50.101827ms
2025-09-26T07:53:08.433 Exec chown -R 1000 /mnt/v/global-commands stdout=, stderr=, err=<nil>
2025-09-26T07:53:09.007 Testing to see if /mnt/ddev_config is properly mounted
2025-09-26T07:53:09.149 Getting stderr output from 'log-stderr.sh --show'
Starting ddev-router if necessary...
2025-09-26T07:53:09.907 Copied /home/andreas/.ddev/traefik:CopyIntoVolume_uaolwsvircug into /mnt/v/traefik in 50.756776ms
2025-09-26T07:53:09.945 Exec chown -R 1000 /mnt/v/traefik stdout=, stderr=, err=<nil>
2025-09-26T07:53:10.218 Copied global Traefik config in /home/andreas/.ddev/traefik/certs to ddev-global-cache/traefik
2025-09-26T07:53:10.337 Waiting for ddev-router to become ready, timeout=60
2025-09-26T07:53:10.849 ddev-router is ready
Successfully started tryddevproject-14541
Your project can be reached at https://tryddevproject-14541.ddev.site
See 'ddev describe' for alternate URLs.


======== curl -I of http://127.0.0.1 from inside container ========
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
HTTP/1.1 200 OK
Server: nginx
Date: Fri, 26 Sep 2025 05:53:14 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Vary: Accept-Encoding



======== curl -I of http://127.0.0.1:49280 (web container http docker bind port) from outside ========
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
HTTP/1.1 200 OK
Server: nginx
Date: Fri, 26 Sep 2025 05:53:14 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Vary: Accept-Encoding



======== curl -I of http://tryddevproject-14541.ddev.site (router http URL) from outside ========
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
HTTP/1.1 200 OK
Content-Type: text/html; charset=UTF-8
Date: Fri, 26 Sep 2025 05:53:14 GMT
Server: nginx
Vary: Accept-Encoding



======== Full curl of http://tryddevproject-14541.ddev.site (router http URL) from outside ========
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   198    0   198    0     0   9768      0 --:--:-- --:--:-- --:--:--  9900
Success accessing database... db via TCP/IP<br />
ddev is working.<br />
The output file for Discord or issue queue is in
<b>/tmp/ddev-debug-test.txt</b><br />
file:///tmp/ddev-debug-test.txt<br />


======== Full curl of https://tryddevproject-14541.ddev.site (router https URL) from outside ========
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.


======== curl -I of https://www.google.com to check internet access and VPN ========
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
HTTP/2 200
content-type: text/html; charset=ISO-8859-1
content-security-policy-report-only: object-src 'none';base-uri 'self';script-src 'nonce-xhORzW_V1ukQnU9LmksbaA' 'strict-dynamic' 'report-sample' 'unsafe-eval' 'unsafe-inline' https: http:;report-uri https://csp.withgoogle.com/csp/gws/other-hp
accept-ch: Sec-CH-Prefers-Color-Scheme
p3p: CP="This is not a P3P policy! See g.co/p3phelp for more info."
date: Fri, 26 Sep 2025 05:53:14 GMT
server: gws
x-xss-protection: 0
x-frame-options: SAMEORIGIN
expires: Fri, 26 Sep 2025 05:53:14 GMT
cache-control: private
set-cookie: AEC=AaJma5vcGA05ONYU4wHaog-8EhEeMinC22NePF684BUoimGNHL4VIwgyU4o; expires=Wed, 25-Mar-2026 05:53:14 GMT; path=/; domain=.google.com; Secure; HttpOnly; SameSite=lax
set-cookie: __Secure-ENID=28.SE=TLFmsP48b2mkwnyD0nDEp6Q9VVlYv0eryNnyf4Ik1DE76PkUu_JlfARs-rK7_cfJzbnkj_y2NS2kT208JXAHKidL7xJZi_m60pz3lq5K7Rq_JsTemJeCPbSAxSu__Dl3W7vhTqUPiMvBJzzKbQCze2IeO4xDiX6Bk2EeDaedtz3--xcvhQt4D7v-A_dfRcrAiHrrhGlCd6BEega0XFG3QX4s0AAoEKkjsEwTO0TMh8H7PQcwQTQ-73pmQx_-uA; expires=Mon, 26-Oct-2026 22:11:32 GMT; path=/; domain=.google.com; Secure; HttpOnly; SameSite=lax
alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000



======== host.docker.internal status ========
PING host.docker.internal (192.168.65.254) 56(84) bytes of data.
64 bytes from 192.168.65.254: icmp_seq=1 ttl=63 time=0.704 ms

--- host.docker.internal ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.704/0.704/0.704/0.000 ms


======== Project ownership on host ========
drwxr-xr-x 4 andreas andreas 4096 Sep 26 07:51 ../tryddevproject-14541


======== Project ownership in container ========
drwxr-xr-x 4 andreas andreas 4096 Sep 26 07:51 //var/www/html


======== In-container filesystem ========
Filesystem     Type  1K-blocks     Used Available Use% Mounted on
/dev/sde       ext4 1055762868 26276796 975782600   3% /var/www/html


======== Thanks for running the diagnostic! ========
Running ddev launch in 3 seconds
Running ddev launch
Waiting for ddev launch to complete before deleting project


Cleanup: deleting test project tryddevproject-14541
 Container ddev-tryddevproject-14541-db  Stopped
 Container ddev-tryddevproject-14541-web  Stopped
 Container ddev-tryddevproject-14541-db  Stopped
 Container ddev-tryddevproject-14541-web  Stopped
 Container ddev-tryddevproject-14541-db  Removed
 Container ddev-tryddevproject-14541-web  Removed
 Network ddev-tryddevproject-14541_default  Removed
Volume tryddevproject-14541-mariadb for project tryddevproject-14541 was deleted
Volume tryddevproject-14541-postgres for project tryddevproject-14541 was deleted
Image ddev/ddev-dbserver-mariadb-10.11:v1.24.8-tryddevproject-14541-built for project tryddevproject-14541 was deleted
Image ddev/ddev-webserver:v1.24.8-tryddevproject-14541-built for project tryddevproject-14541 was deleted
Project tryddevproject-14541 was deleted. Your code and configuration are unchanged.
Optionally, run `docker builder prune` to clean unused builder cache.

Please remove the files from this test with 'rm -r ../tryddevproject-14541'
```
</details>

### Expected Behavior

The command `ddev auth ssh` should add the SSH keys to the container.

### Actual Behavior

Currently there is the problem that `ddev auth ssh` hangs on WSL2 using Windows - if you try to execute the command it hangs for a long time and nothing happens. I have to break it with `Strg + C` to make my console work again. We have it configured as a post-start-hook but also if you run the command in the console.

### Steps To Reproduce

1. In WSL2 for Windows 11
2. Run the command `ddev auth ssh`
3. The command hangs until you press `Ctrl + C`.
4. Failed to execute command `ddev auth ssh`: container run failed with exit code 130

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by stasadev**
## The Issue

- #7664

## How This PR Solves The Issue

- Adds detailed output for each key before running `ssh-add`.
- Runs start only after attach for ssh container.
- Ensures that we have `ddev/ddev-ssh-agent`, because it doesn't show that it pulls it when there are no DDEV images.
- Fixes `ddev auth ssh -j` output. (It should always be JSON compatible.)

## Manual Testing Instructions

Prepare keys:

- `key1` has "key1" passphrase
- `key2` has "key2" passphrase

```
ssh-keygen -t rsa -b 4096 -C "key1@example.com" -f ./key1 -N "key1"
ssh-keygen -t rsa -b 4096 -C "key2@example.com" -f ./key2 -N "key2"
```

See new output "Running: ssh-add key1", "Running: ssh-add key2":

```
$ ddev auth ssh -d .
Adding 2 SSH private key(s)... 
Adding key key1
Enter passphrase for key1: 
Identity added: key1 (key1@example.com)
Adding key key2
Enter passphrase for key2: 
Identity added: key2 (key2@example.com)
Successfully added 2 SSH private key(s).
```

---

`ddev auth ssh` silently pulled the image (when there was no such image), which was wrong. Now it shows the actual pull:

```
$ ddev delete images -a && ddev auth ssh
Network ddev_default created 
[+] Pulling 7/7
 ✔ ddev-ddev-ssh-agent-v1.24.8 Pulled                                      2.9s 
   ✔ d107e437f729 Already exists                                           0.0s 
   ✔ 86a0fbc39b3e Already exists                                           0.0s 
   ✔ f299420bc9df Already exists                                           0.0s 
   ✔ 4f4fb700ef54 Already exists                                           0.0s 
   ✔ 4730d8ececd6 Already exists                                           0.0s 
   ✔ ccef343c5ffd Already exists                                           0.0s 
 Container ddev-ssh-agent  Created 
 Container ddev-ssh-agent  Started
...
```

### CODE REVIEW

**Comment by rfay** [comment]
Rebased.

File: cmd/ddev/cmd/auth-ssh.go [hunk 1]
```diff
@@ -190,7 +190,7 @@ func runSSHAuthContainer(keys []string) (int, error) {
 	uidStr, _, _ := util.GetContainerUIDGid()
 	config := &dockerContainer.Config{
 		Image:       docker.GetSSHAuthImage() + "-built",
-		Cmd:         dockerStrslice.StrSlice{"bash", "-c", `cp -r /tmp/sshtmp ~/.ssh && chmod -R go-rwx ~/.ssh && cd ~/.ssh && mapfile -t keys < <(grep -l '^-----BEGIN .* PRIVATE KEY-----' *) && ((${#keys[@]})) || { echo "No SSH private keys found" >&2; exit 1; } && for key in "${keys[@]}"; do ssh-add "$key" || exit $?; done`},
+		Cmd:         dockerStrslice.StrSlice{"bash", "-c", `cp -r /tmp/sshtmp ~/.ssh && chmod -R go-rwx ~/.ssh && cd ~/.ssh && mapfile -t keys < <(grep -l '^-----BEGIN .* PRIVATE KEY-----' *) && ((${#keys[@]})) || { echo "No SSH private keys found" >&2; exit 1; } && for key in "${keys[@]}"; do printf "\nRunning command: ssh-add %s\n" "$key"; ssh-add "$key" || exit $?; done`},
```
Comment (rfay) [inline cmd/ddev/cmd/auth-ssh.go]: Most people don't know what `ssh-add` is or what it means in this context. Maybe simplify to "Adding key %s" ?

Comment (stasadev) [reply cmd/ddev/cmd/auth-ssh.go]: Done.

In addition, I fixed the output for `ddev auth ssh -j`, it should only produce JSON output.

**Comment by rfay** [comment]
On my first attempt to test this I got this:

```
rfay@ubuntu-len:~/workspace/ddev$ ddev auth ssh
[+] Pulling 0/1
[+] Pulling 0/1 ⠋ ddev-ddev-ssh-agent-20250824_akibaat_buildx_arm_builder-built Pulling
[+] Pulling 0/1 ⠙ ddev-ddev-ssh-agent-20250824_akibaat_buildx_arm_builder-built Pulling
[+] Pulling 0/1 ⠹ ddev-ddev-ssh-agent-20250824_akibaat_buildx_arm_builder-built Pulling
[+] Pulling 0/1 ⠸ ddev-ddev-ssh-agent-20250824_akibaat_buildx_arm_builder-built Pulling
[+] Pulling 0/1 ⠼ ddev-ddev-ssh-agent-20250824_akibaat_buildx_arm_builder-built Pulling
[+] Pulling 0/1 ⠴ ddev-ddev-ssh-agent-20250824_akibaat_buildx_arm_builder-built Pulling
[+] Pulling 0/1 ⠦ ddev-ddev-ssh-agent-20250824_akibaat_buildx_arm_builder-built Pulling
[+] Pulling 0/1 ⠧ ddev-ddev-ssh-agent-20250824_akibaat_buildx_arm_builder-built Pulling
[+] Pulling 0/1 ⠇ ddev-ddev-ssh-agent-20250824_akibaat_buildx_arm_builder-built Pulling
[+] Pulling 0/1 ⠏ ddev-ddev-ssh-agent-20250824_akibaat_buildx_arm_builder-built Pulling
[+] Pulling 0/1 ⠋ ddev-ddev-ssh-agent-20250824_akibaat_buildx_arm_builder-built Pulling
[+] Pulling 0/1 ⠙ ddev-ddev-ssh-agent-20250824_akibaat_buildx_arm_builder-built Pulling
[+] Pulling 0/1 ⠹ ddev-ddev-ssh-agent-20250824_akibaat_buildx_arm_builder-built Pulling
[+] Pulling 1/1 ⠸ ddev-ddev-ssh-agent-20250824_akibaat_buildx_arm_builder-built Pulling
          1.4s  ✘ ddev-ddev-ssh-agent-20250824_akibaat_buildx_arm_builder-built Error manifest for ddev/ddev-ssh-agent:20250824_akibaat_buildx_arm_builder-built not found: manifest unknown: manifest unknown1.5s
                                                                                           Error response from daemon: manifest for ddev/ddev-ssh-agent:20250824_akibaat_buildx_arm_builder-built not found: manifest unknown: manifest unknown
                                                                                                                       Failed to execute command `ddev auth ssh`: failed to pull image ddev/ddev-ssh-agent:20250824_akibaat_buildx_arm_builder-built: exit status 1
                                                                                                                       
```
