### PR TITLE
Revert parent config search, prevent directory destruction, hopefully fixes #1574

### LINKED ISSUE #1574: DDEV deleted everything in my home directory
**Describe the bug**

DDEV seems to have picked up the wrong directory path and nuked everything in my home directory rather than in the new project directory.

* Just finished installing docker, docker-compose, ddev on a relatively new laptop.
* Tried to initialise a new D8 project.
* Followed the steps as described in the docs at https://ddev.readthedocs.io/en/stable/users/cli-usage/#drupal-8-quickstart.

**To Reproduce**
```
 $ ~/projects  mkdir d8site

 $ ~/projects cd d8site 

 $ ~/projects/d8site ddev config --project-type php --php-version 7.1
You are reconfiguring the project at /home/jpoesen. 
The existing configuration will be updated and replaced. 
Found a php codebase at /home/jpoesen/projects/d8site 
Project type has no settings paths configured, so not creating settings file. 
Configuration complete. You may now run 'ddev start'. 

~/projects/d8site ddev composer create drupal-composer/drupal-project:8.x-dev --stability dev --no-interaction
Warning: Any existing contents of the project root (/home/jpoesen) will be removed 
Removing any existing files in project root 
Failed to create project: permission denied 
```

Because of 'no-interaction', at this point everything in /home/jpoesen is erased. 
If I had run this without no-interaction I might have spotted that /home/jpoesen was about to get nuked.

**Version and configuration information (please complete the following information):*
- Host OS: ubuntu bionic
- Docker version 18.09.5, build e8ff056
- ddev v1.7.1

Happy to help troubleshoot. As long as the root cause (which may well be something on my end) is not found, I can't trust ddev anymore, understandably, since all my downloads, project files, ... got nuked.

Thanks.

### PR DESCRIPTION
**Pull request by rfay**
## The Problem/Issue/Bug:

In #1574 a user reported destruction of their entire home directory by a `ddev composer create` command that mistakenly operated on the home directory.

## How this PR Solves The Problem:

* Revert #1275, which allowed automatic searching of parent directories for a project.
* Instead, do the search and note the results during `ddev config`
* Prevent users from using `ddev config` in their home directory.
* Remove the --no-interaction behavior from `ddev composer create` that allows wholesale destruction without the user saying "ok".

## Manual Testing Instructions:

* Try `ddev config` in home directory.
* Create a ~/junk folder and `ddev config` in it. Then create ~/junk/sub1 and `ddev config` in it. It should be willing to config, but warn about the existing parent.
* Run `ddev composer create --no-interaction`. The composer portion should run without interaction, but when it comes to delete time, it needs to require your OK. 

## Automated Testing Overview:

This definitely needs some tests:
- [x] Try ddev config in home directory
- [x] Try ddev config in a subdirectory of a project
- [ ] Make sure `ddev composer create --no-interaction` requires interaction before deletion.

## Related Issue Link(s):

OP #1574 "Ddev deleted everything in my home directory"

### CODE REVIEW

File: cmd/ddev/cmd/config.go [hunk 1]
```diff
@@ -258,24 +265,20 @@ func init() {
...
 
-	// Check for an existing config in this or a parent dir
-	appRoot, err := ddevapp.CheckForConf(cd)
-	if err != nil {
-		// An error indicates no config file was found, use current directory
-		appRoot = cd
+	// Check for an existing config in a parent dir
+	otherRoot, _ := ddevapp.CheckForConf(appRoot)
+	if otherRoot != appRoot {
+		util.Error("Is it possible you wanted to `ddev config` in parent directory %s?", otherRoot)
```
Comment (andrewfrench) [inline cmd/ddev/cmd/config.go]: This confirmation isn't working for me. When I run `ddev config` in a new directory, I get this warning:

```
Is it possible you wanted to `ddev config` in parent directory ?
```

Note the empty value being passed to the format string. I can walk up the directory stack and get the warning in every directory (`~/junk/abc/def`, `~/junk/abc`, `~/junk`), except the home directory, where it fails with:

```
Is it possible you wanted to `ddev config` in parent directory ?
could not create new config: ddev config is not useful in home directory (/Users/andrew)
```

**Comment by rfay** [comment]
Hmm @andrewfrench I have this behavior, which looks right to me, maybe you used a different technique, I'll try looking for the technique you used:

```
rfay@rfay-mbp-2017:~/workspace/d8git/modules/backup_migrate$ ddev config
Is it possible you wanted to `ddev config` in parent directory /Users/rfay/workspace/d8git?
Creating a new ddev project config in the current directory (/Users/rfay/workspace/d8git/modules/backup_migrate)
Once completed, your configuration will be written to /Users/rfay/workspace/d8git/modules/backup_migrate/.ddev/config.yaml
```

**Comment by rfay** [comment]
Ah, I definitely find the behavior when there *is* no parent ddev-config directory. I'll fix that for sure. I think that's what you saw.
