### PR TITLE
fix: sort web_extra_exposed_ports for router port matching in generic webserver, fixes #7640

### LINKED ISSUE #7640: Prefer default pair of router ports from `web_extra_exposed_ports` for `generic` webserver
From Discord: https://discord.com/channels/664580571770388500/1418328103671042179/1418562922124148766

> Actually, the only "issue" I have is that, for some reason, DDEV sets the default web port to 8080 - so something like `https://my-app.ddev.site:8080`
> Just to clarify, everything works as expected in the normal ports (80/443), it's just a small nitpick. 

> I think it picks it up from
```yaml
web_extra_exposed_ports:
  - name: reverb
    container_port: 8080
    http_port: 8081
    https_port: 8080
```
> but only when I'm using the generic web server.

----

> We have configuration to pickup first pair of ports from `web_extra_exposed_ports` (whatever they are).
If you move this `web_extra_exposed_ports` from `.ddev/config.yaml` to `.ddev/config.reverb.yaml` it should be added after `.ddev/config.frankenphp.yaml`, and hopefully `80/443` will be used.

---

I added this feature in:

- #7171

Need to review the logic for `web_extra_exposed_ports` + `generic` webserver to prefer the default pair of router ports.

### PR DESCRIPTION
**Pull request by stasadev**
## The Issue

- #7640

I used the first pair of ports in:

- #7171

This is a good solution, but not good enough, because it depends on the order of `web_extra_exposed_ports` items.

## How This PR Solves The Issue

Sorts `web_extra_exposed_ports` before using them, to ensure that first pair of ports matches router ports in generic webserver.

## Manual Testing Instructions

Testing standard 80/443 router ports:

```bash
ddev config --auto
cat > .ddev/config.a.yaml <<'EOF'
web_extra_exposed_ports:
  - name: reverb
    container_port: 12345
    http_port: 12345
    https_port: 12346
EOF
ddev add-on get ddev/ddev-frankenphp
ddev restart
ddev exec 'env | grep DDEV_ROUTER'
```

Before:

```
DDEV_ROUTER_HTTP_PORT=12345
DDEV_ROUTER_HTTPS_PORT=12346
```

After

```
DDEV_ROUTER_HTTP_PORT=80
DDEV_ROUTER_HTTPS_PORT=443
```

---

Testing custom 8080/8443 router ports:

```bash
ddev config --auto
cat > .ddev/config.a.yaml <<'EOF'
router_http_port: "8080"
router_https_port: "8443"
web_extra_exposed_ports:
  - name: reverb
    container_port: 12345
    http_port: 12345
    https_port: 12346
EOF
ddev add-on get ddev/ddev-frankenphp
sed -i 's/http_port: 80/http_port: 8080/' .ddev/config.frankenphp.yaml
sed -i 's/https_port: 443/https_port: 8443/' .ddev/config.frankenphp.yaml
ddev restart
ddev exec 'env | grep DDEV_ROUTER'
```

Before:

```
DDEV_ROUTER_HTTP_PORT=12345
DDEV_ROUTER_HTTPS_PORT=12346
```

After

```
DDEV_ROUTER_HTTP_PORT=8080
DDEV_ROUTER_HTTPS_PORT=8443
```

### CODE REVIEW

**Review by tyler36 — APPROVED** [review]
Confirmed.

- Followed "Manual Testing" steps.
- Was able to reproduce issue with current DDEV (`v1.24.10`).
- Confirmed expected outcome with this PR (`v1.24.10-127-gebd738f2f`)

File: pkg/ddevapp/router.go [hunk 1]
```diff
@@ -674,3 +683,51 @@ func SyncGenericWebserverPortsWithRouterPorts(app *DdevApp) {
 		}
 	}
 }
+
+// SortWebExtraExposedPorts sorts WebExtraExposedPorts so the entry matching
+// the configured router ports comes first (index 0).
+//
+// This is called during app initialization to ensure AssignRouterPortsToGenericWebserverPorts
```
Comment (stasadev) [inline pkg/ddevapp/router.go]:
```suggestion
// This is called by app.ReadConfig to ensure AssignRouterPortsToGenericWebserverPorts
```

File: pkg/ddevapp/router.go [hunk 2]
```diff
@@ -674,3 +683,51 @@ func SyncGenericWebserverPortsWithRouterPorts(app *DdevApp) {
...
+	if preferredHTTPS == "" {
+		preferredHTTPS = globalconfig.DdevGlobalConfig.RouterHTTPSPort
+	}
+	if preferredHTTPS == "" {
+		preferredHTTPS = nodeps.DdevDefaultRouterHTTPSPort
+	}
+	httpPort, _ := strconv.Atoi(preferredHTTP)
+	httpsPort, _ := strconv.Atoi(preferredHTTPS)
+
+	slices.SortStableFunc(app.WebExtraExposedPorts, func(a, b WebExposedPort) int {
```
Comment (stasadev) [inline pkg/ddevapp/router.go:720]:
```suggestion
	// Sort ports so the best match for the requested HTTP/HTTPS ports comes first.
	// The order is stable, so ports with the same match quality keep their
	// original relative order.
	slices.SortStableFunc(app.WebExtraExposedPorts, func(a, b WebExposedPort) int {
```

File: pkg/ddevapp/router.go [hunk 3]
```diff
@@ -674,3 +683,51 @@ func SyncGenericWebserverPortsWithRouterPorts(app *DdevApp) {
...
+			aMatch = 2
+		} else if a.HTTPPort == httpPort || a.HTTPSPort == httpsPort {
+			aMatch = 1
+		}
+		if b.HTTPPort == httpPort && b.HTTPSPort == httpsPort {
+			bMatch = 2
+		} else if b.HTTPPort == httpPort || b.HTTPSPort == httpsPort {
+			bMatch = 1
+		}
+		return bMatch - aMatch // Higher match comes first
```
Comment (stasadev) [inline pkg/ddevapp/router.go]:
```suggestion
		// Sort in descending order so higher-quality matches appear first
		return bMatch - aMatch
```

File: pkg/ddevapp/router.go [hunk 4]
```diff
@@ -674,3 +683,51 @@ func SyncGenericWebserverPortsWithRouterPorts(app *DdevApp) {
...
+	if preferredHTTPS == "" {
+		preferredHTTPS = nodeps.DdevDefaultRouterHTTPSPort
+	}
+	httpPort, _ := strconv.Atoi(preferredHTTP)
+	httpsPort, _ := strconv.Atoi(preferredHTTPS)
+
+	slices.SortStableFunc(app.WebExtraExposedPorts, func(a, b WebExposedPort) int {
+		aMatch := 0
+		bMatch := 0
+		// Full match = 2, partial = 1, none = 0
```
Comment (stasadev) [inline pkg/ddevapp/router.go]:
```suggestion

		// Match scoring:
		// 2 = both HTTP and HTTPS ports match exactly
		// 1 = either HTTP or HTTPS port matches
		// 0 = no match at all
```
