### PR TITLE
Set NFS wsize/rsize options for Ventura (Fixes #4122)

### LINKED ISSUE #4122: macOS Ventura + nfs_mount_enabled: 504 Error on laravel and bedrock sites
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

https://gist.github.com/shayanabbas/5f7e4481027cce533824b845c76e1186

### Current Behavior

This is the most weirdest issue I have ever had.

I am trying to run my bedrock projects, everything was working fine until I updated to macOS Ventura

After lot of debugging and trying everything it seems like when ever I try to run a laravel and bedrock project the browsers keep loading and show 504 error.

### Expected Behavior

it should run out of the box, i am not sure what macOS Ventura might have changed?

### Steps To Reproduce

I have tried creating fresh projects of Drupal, Wordpress, Bedrock, Laravel  from Quick Start guide 
https://ddev.readthedocs.io/en/latest/users/quickstart/

Drupal and Wordpress (simple) are working and running

where as Bedrock and Laravel project runs successfully but when I visit in browser it keeps loading until it shows a 504 error page.

I tried changing with both nginx and apace webserver configuation in config.yaml

Server is working fine because when I put a index.php file with php info function, it does show that page. but as soon as I change it back to default laravel or bedrock it agains keeps showing 504 error.

I have updated version of ddev and dockers and docker is also has plenty of extra space assigned.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by karlshea**
## The Problem/Issue/Bug:

* #4122 

## How this PR Solves The Problem:

Sets `wsize`/`rsize` to 32768

## Manual Testing Instructions:

See 
* #4122 

## Automated Testing Overview:

@rfay unsure how you'd like to test. I've been using a 100MB zip file and running md5sum on it from inside a container, but I bet you don't want a 100MB object in the git repo 🙃

## Related Issue Link(s):

* #4122
* docker/for-mac#6544

## Release/Deployment notes:

Existing NFS volumes would need to be deleted/recreated to pick up the new options.

<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4359"></a>

### CODE REVIEW

**Comment by karlshea** [comment]
Looks like Docksal has a similar PR: docksal/docksal#1728

**Comment by rfay** [comment]
Awesome! Should be easy to generate a large file. 

A quick manual test with bedrock with and without this showed that this solves at least the trivial problem.

But I think I'll just upgrade the test runners to Ventura, and that a clearer test. 

@karlshea could you please add more detail to https://github.com/docker/for-mac/issues/6544 explaining where the default values come from, where they come from in recent docker and macOS?

File: pkg/dockerutil/dockerutils_test.go [hunk 1]
```diff
@@ -509,7 +509,7 @@ func TestRemoveVolume(t *testing.T) {
 	if runtime.GOOS == "darwin" && fileutil.IsDirectory(filepath.Join("/System/Volumes/Data", source)) {
 		source = filepath.Join("/System/Volumes/Data", source)
 	}
-	volume, err := CreateVolume(testVolume, "local", map[string]string{"type": "nfs", "o": "addr=host.docker.internal,hard,nolock,rw",
+	volume, err := CreateVolume(testVolume, "local", map[string]string{"type": "nfs", "o": "addr=host.docker.internal,hard,nolock,rw,wsize=32768,rsize=32768",
```
Comment (rfay) [inline pkg/dockerutil/dockerutils_test.go:512]: Glad you discovered this; it wasn't right for some environments.
```suggestion
        nfsServerAddr, _ := dockerutils.GetNFSServerAddr()
	volume, err := CreateVolume(testVolume, "local", map[string]string{"type": "nfs", "o": fmt.Sprintf("addr=%s,hard,nolock,rw,wsize=32768,rsize=32768", nfsServerAddr),
```

**Review by rfay — CHANGES_REQUESTED** [review]
Looking great. I think these two comments will improve it. If they break anything I'll fix it :)

**Comment by karlshea** [comment]
> @karlshea could you please add more detail to [docker/for-mac#6544](https://github.com/docker/for-mac/issues/6544) explaining where the default values come from, where they come from in recent docker and macOS?

That's a good call, check out my latest reply because it's interesting. We're actually *lowering* the default values that Docker sets.

**Comment by rfay** [comment]
Mac test runners are all upgraded to Ventura now.

**Comment by rfay** [comment]
However, the standard mac check is shortcutted and doesn't test any of the CMSs that failed, like laravel.

**Comment by rfay** [comment]
There are some problems being detected by tests now. I haven't been able to recreate them on my local machine, so obviously I have some fun ahead.

**Comment by karlshea** [comment]
It looks like one of those is a command line tools issue—I had the same problem locally after upgrading, it seemed like softwareupdate didn't see it so I had to launch XCode to get it installed.

**Comment by rfay** [comment]
Yeah, I think I got all those fixed.

**Comment by rfay** [comment]
On macstadium-m1 we're seeing this: `o: "addr=,hard,nolock,rw,wsize=32768,rsize=32768"` (no IP address) which I'm sure is a result of the change I made to not fall back to host.docker.internal.

**Comment by rfay** [comment]
It turned out I was testing with Colima, not Docker Desktop, which has different characteristics for determining the NFS server. That's why I couldn't demonstrate the problem. But when I used Docker Desktop it was easy to see.

**Comment by rfay** [comment]
One request @karlshea - When you make a PR, make a branch first, so the branch name of your PR isn't "master". That will help *you* the next time you create a PR (because you won't be confused what branch is what) but it will help here because your PR having the name "master" confused the dickens out of buildkite, which kept killing off jobs in the upstream/master branch when new ones were started in this PR.

**Comment by karlshea** [comment]
Ahhh sorry! Branches are my normal workflow but I forked and committed in a rush this time.

**Comment by karlshea** [comment]
I can retarget this PR if that would make getting the tests right easier?

**Comment by rfay** [comment]
I found out the setting that prevents this in buildkite and now I actually understand why it exists!

**Comment by rfay** [comment]
Didn't re-enable commented section in TestNFSMount and it got committed, so WSL2 was tested with NFS :(

**Comment by rfay** [comment]
Thanks so much @karlshea for tracking this down. Very impressive work and very much appreciated. It looks like it's going to pass everything (that I messed up) now. Let me know when you think it's ready to pull. Then it will be easily accessible to people with `brew unlink ddev && brew install --HEAD --fetch-head ddev`
