### PR TITLE
Copy targets of symlinked files in .homeadditions. Fixes #3903

### LINKED ISSUE #3903: Webserver fails to start with symlink in global homeadditions
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

I had been linking my .gitconfig file using `ln -s ~/.gitconfig ~/.ddev/homeadditions/.gitconfig` to create a symlink. This adds my up-to-date .gitconfig to my global DDEV homeadditions.

Recently, web containers no longer build and start successfully, and I get this error on every web container:

> cp: '/mnt/ddev_config/.homeadditions/./.gitconfig' and '/home/kali/./.gitconfig' are the same file

**Gist:** https://gist.github.com/mbomb007/d8fa53fac541271ffe53bbcd5ee34e05

### Current Behavior

I had been linking my .gitconfig file using `ln -s ~/.gitconfig ~/.ddev/homeadditions/.gitconfig` ([see this DDEV issue comment here](https://github.com/drud/ddev/issues/1459#issuecomment-805260856)), but now it causes web containers to fail to start with this error:

> cp: '/mnt/ddev_config/.homeadditions/./.gitconfig' and '/home/kali/./.gitconfig' are the same file

### Expected Behavior

I expect to see the symlinked .gitconfig file copied to my Docker containers, allowing my per-user settings to be used within containers.

### Steps To Reproduce

1. Create a .gitconfig in WSL2
2. Symlink to it in the DDEV global homeadditions: `ln -s ~/.gitconfig ~/.ddev/homeadditions/.gitconfig`
3. `ddev config`
4. `ddev start`
5. Webserver fails to start, showing:

> cp: '/mnt/ddev_config/.homeadditions/./.gitconfig' and '/home/kali/./.gitconfig' are the same file

I then verified this is the issue by removing the symlink, removing the container, reconfiguring, and recreating the container. It works fine. But I don't understand why there's an issue copying the file to the container.

### Anything else?

**Gist:** https://gist.github.com/mbomb007/d8fa53fac541271ffe53bbcd5ee34e05

Viewing the logs of the ddev-webserver container that failed to start for tryddevproject shows this at the end:

```
...
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
+ '[' -d /mnt/ddev_config/.homeadditions ']'
+ cp -r /mnt/ddev_config/.homeadditions/. /home/kali/
cp: '/mnt/ddev_config/.homeadditions/./.gitconfig' and '/home/kali/./.gitconfig' are the same file
```

### PR DESCRIPTION
**Pull request by mbomb007**
## The Problem/Issue/Bug:

Symlinked files are not copied to the container from the .homeadditions folder. It throws an error.

## How this PR Solves The Problem:

The `-L` flag was added to `cp` so that symlinks are followed when copying.

## Manual Testing Instructions:

Add a symlink in the global homeadditions folder with a command like this: 

```bash
ln -s ~/.gitconfig ~/.ddev/homeadditions/.gitconfig
```

Then, configure DDEV and start a webserver container

```bash
ddev config
ddev start
```

## Automated Testing Overview:

I did not add any tests. I don't know how.

## Related Issue Link(s):

- https://github.com/drud/ddev/issues/1459
- https://github.com/drud/ddev/issues/3903

## Release/Deployment notes:

<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3904"></a>

### CODE REVIEW

**Review by rfay — CHANGES_REQUESTED** [review]
To test this properly you'll have to push a ddev-webserver image and edit pkg/versionconstants/versionconstants.go to point to it. It's not hard, https://ddev.readthedocs.io/en/latest/developers/building-contributing/#docker-image-changes

Then you can build and test it...

**Comment by rfay** [comment]
I'll change and push then and you can test it.

**Comment by rfay** [comment]
Pushed an image, updated version.go, rebased. 

Now it needs manual testing to see if you like it @mbomb007 

Then it needs to have this case added to the automated tests.

File: containers/ddev-webserver/ddev-webserver-base-scripts/start.sh [hunk 1]
```diff
@@ -88,7 +88,7 @@ if [ ! -f ${NVM_DIR:-${HOME}/.nvm}/nvm.sh ]; then (install_nvm.sh || true); fi
 # should all be set up with both global and local
 # either way.
 if [ -d /mnt/ddev_config/.homeadditions ]; then
-    cp -r /mnt/ddev_config/.homeadditions/. ~/
+    cp -rL /mnt/ddev_config/.homeadditions/. ~/
```
Comment (rfay) [inline containers/ddev-webserver/ddev-webserver-base-scripts/start.sh:91]: Unfortunately this approach can't work as it is. The fact is that the symlink (/mnt/ddev_config/.homeadditions/.ssh/config, for example) is already disconnected from the source, because it's mounted into the container where the symlink can't be followed. For this to work, the copy has to be done on the host side, not by following the symlink here.

**Review by rfay — CHANGES_REQUESTED** [review]
I may spend just  a little more time looking at this, but as it is it's not going to work. Happy to continue the conversation.

**Review by rfay — APPROVED** [review]
I reverted what was done and used a host-side approach to do the same thing, added tests. Please download the artifacts and test and see if you like it @mbomb007 .

**Comment by stasadev** [comment]
It works really nice, I tested this with the **ddev-linux-amd64** artifact:

- `ln -s ~/.gitconfig ~/.ddev/homeadditions/.gitconfig`
- `mkdir -p ~/.ddev/homeadditions/.ssh && ln -s ~/.ssh/config ~/.ddev/homeadditions/.ssh/config`
- symlink to `~/.gitconfig` in another symlink folder (becomes a regular file as expected) `mkdir ~/test && ln -s ~/.gitconfig ~/test/.gitconfig && ln -s ~/test ~/.ddev/homeadditions/test`
- broken symlink (failed to start the project as expected) `ln -s ~/.gitconfig2 ~/.ddev/homeadditions/.gitconfig2`

I tested the same with symlinks in `$DDEV_APPROOT/.ddev/homeadditions`, works too.

**Comment by stasadev** [comment]
It works really nice, I tested this with the **ddev-linux-amd64** artifact:

- `ln -s ~/.gitconfig ~/.ddev/homeadditions/.gitconfig`
- `mkdir -p ~/.ddev/homeadditions/.ssh && ln -s ~/.ssh/config ~/.ddev/homeadditions/.ssh/config`
- symlink to `~/.gitconfig` in another symlink folder (becomes a regular file as expected) `mkdir ~/test && ln -s ~/.gitconfig ~/test/.gitconfig && ln -s ~/test ~/.ddev/homeadditions/test`
- broken symlink (failed to start the project as expected) `ln -s ~/.gitconfig2 ~/.ddev/homeadditions/.gitconfig2`

I tested the same with symlinks in `$DDEV_APPROOT/.ddev/homeadditions`, works too.

**Comment by rfay** [comment]
Thanks for making it happen @mbomb007 !
