### PR TITLE
Touch up Windows WSL2 hosts file support and docs, rename DRUD_INTERACTIVE, fixes #2533

### LINKED ISSUE #2533: Non-ddev.site hostnames can't work on WSL2, and neither can ddev.site if DNS rebinding disallowed
**Describe the bug**

When the hostname required for a project is not *.ddev.site, or when DNS rebinding is not allowed, WSL2 browser stuff can't work.

So:
1. If DNS rebinding is disallowed, ddev will add the hostname to /etc/hosts. But unfortunately it's the /etc/hosts in the WSL2 system, which is *not* the hosts file that the browser will use (which is C:\Windows\System32\drivers\etc\hosts). So the browser can't recognize it.
2. If project_tld is set to something other than ddev.site, same problem
3. If additional_fqdns is set, that has the same problem.

I'm not sure there's a good solution to this, because WSL2 code can't change things on the Windows side...

Windows users can work around this issue by manually adding the needed hostnames to C:\Windows\System32\drivers\etc\hosts or by using the *windows* ddev to issue the command `ddev hostname <neededfqdn> 127.0.0.1`

### PR DESCRIPTION
**Pull request by rfay**
## The Problem/Issue/Bug:

#2533: In the current state of WSL2, there's quite a lot of confusion in the computer about how to look up hostnames. However, ddev already has warnings to users, and it rarely matters to users who use *.ddev.site.

## How this PR Solves The Problem:

* Improved docs, minor addition to code that warns WSL2 users
* Rename DRUD_INTERACTIVE  environment variable to DDEV_INTERACTIVE

### CODE REVIEW

File: pkg/ddevapp/ddevapp.go [hunk 1]
```diff
@@ -1988,8 +1988,8 @@ func addHostEntry(name string, ip string) error {
 	util.CheckErr(err)
 
 	output.UserOut.Printf("ddev needs to add an entry to your hostfile.\nIt will require administrative privileges via the sudo command, so you may be required\nto enter your password for sudo. ddev is about to issue the command:")
-	if os.Getenv("WSL_DISTRO") != "" {
-		output.UserOut.Printf("You are on WSL2, so should manually execute 'sudo ddev hostname %s %s' on Windows", name, ip)
+	if nodeps.IsWSL2() {
+		util.Warning("You are on WSL2, so should also manually execute 'sudo ddev hostname %s %s' on Windows if you use a Windows browser.", name, ip)
```
Comment (pointmetothedocs) [inline pkg/ddevapp/ddevapp.go:1992]: how does one execute sudo on windows?
