### PR TITLE
ConfigFileOverrideAction() should only override if no config exists yet, fixes #900

### LINKED ISSUE #900: ddev config on an existing config updates the php version inappropriately
**Describe the bug**

`ddev config` with an existing configuration should respect most settings, certainly php version. 

However, it's updating in some situations, but not all.

Thanks to @jeffsheltren for finding and describing this.

**To Reproduce**

Drupal 7:
* Set the php_version in an existing config.yaml to 5.6
* Run ddev config and click through
* Note that the php_version is now set to 7.1

Drupal 6:
* Set the php_version in an existing config.yaml to 7.0
* Run ddev config and click through
* note the php_version is now set to 5.6

It doesn't seem to happen with Drupal 8. 

**Expected behavior**

Most config.yaml settings should be preserved by ddev config. Certainly php_version

**Version and configuration information (please complete the following information):**
 - Host computer OS and Version: macOS High Sierra
 - Docker version: 18.03
 - ddev version: v0.19.0

### PR DESCRIPTION
**Pull request by rfay**
## The Problem/Issue/Bug:

#900 - ddev config incorrectly updates php version in some situations.

## How this PR Solves The Problem:

ConfigOverrideAction() really should only override on a new config, and had only been used for D7 and D6. Both places it didn't work correctly.

It now only does its job if the config doesn't already exist.

## Manual Testing Instructions:

Described in OP #900 

## Automated Testing Overview:

TestPostConfigAction() tests the expected behavior of ConfigFileOverrideAction().

## Related Issue Link(s):

OP #900

### CODE REVIEW

File: pkg/ddevapp/apptypes_test.go [hunk 1]
```diff
@@ -44,3 +48,54 @@ func TestApptypeDetection(t *testing.T) {
...
+		"wordpress": ddevapp.DdevDefaultPHPVersion,
+		"backdrop":  ddevapp.DdevDefaultPHPVersion,
+	}
+
+	for appType, expectedPHPVersion := range appTypes {
+		testDir := testcommon.CreateTmpDir("TestApptype")
+
+		// testcommon.Chdir()() and CleanupDir() checks their own errors (and exit)
+		defer testcommon.CleanupDir(testDir)
+		defer testcommon.Chdir(testDir)()
```
Comment (andrewfrench) [inline pkg/ddevapp/apptypes_test.go]: This may be what you intend, but these deferred calls won't be executed until after the entire test is complete (when `TestPostConfigAction` returns) and not at the end of the block.

Comment (rfay) [reply pkg/ddevapp/apptypes_test.go]: Yes, that pattern is used all over the place, it's just what we did back in the day. The cleanup after test completion is fine, it's all just about cleaning up the various crap directories.
