### PR TITLE
Better error handling when opening/writing config files, fixes  #1177

### LINKED ISSUE #1177: ddev config fails on Windows with a panic
**Describe the bug**
Project Type [wordpress, typo3, backdrop, php, drupal6, drupal7, drupal8] (php):                                                                                                                                                                                                drupal8
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0xa19c45]

goroutine 1 [running]:
github.com/drud/ddev/pkg/ddevapp.(*DdevApp).CreateSettingsFile(0xc0001a1380, 0x0                                                                                                                                                                                               , 0x0, 0x0, 0x0)
        /go/src/github.com/drud/ddev/pkg/ddevapp/apptypes.go:104 +0x585
github.com/drud/ddev/cmd/ddev/cmd.handleConfigRun(0x1426ea0, 0x1453620, 0x0, 0x0                                                                                                                                                                                               )
        /go/src/github.com/drud/ddev/cmd/ddev/cmd/config.go:111 +0x2f8
github.com/drud/ddev/vendor/github.com/spf13/cobra.(*Command).execute(0x1426ea0,                                                                                                                                                                                                0x1453620, 0x0, 0x0, 0x1426ea0, 0x1453620)
        /go/src/github.com/drud/ddev/vendor/github.com/spf13/cobra/command.go:76                                                                                                                                                                                               6 +0x2d3
github.com/drud/ddev/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1428fe0                                                                                                                                                                                               , 0xc000209f88, 0x405537, 0xc000064058)
        /go/src/github.com/drud/ddev/vendor/github.com/spf13/cobra/command.go:85                                                                                                                                                                                               2 +0x304
github.com/drud/ddev/vendor/github.com/spf13/cobra.(*Command).Execute(0x1428fe0,                                                                                                                                                                                                0x0, 0x0)
        /go/src/github.com/drud/ddev/vendor/github.com/spf13/cobra/command.go:80                                                                                                                                                                                               0 +0x32
github.com/drud/ddev/cmd/ddev/cmd.Execute()
        /go/src/github.com/drud/ddev/cmd/ddev/cmd/root.go:105 +0x42
main.main()
        /go/src/github.com/drud/ddev/cmd/ddev/main.go:6 +0x27

**To Reproduce**
1. ddev config
2. ...
3. enter drupal8

**Version and configuration information (please complete the following information):**
 - Windows 10
 - Docker 18.06.1-ce
 - ddev version 1.3.0

### PR DESCRIPTION
**Pull request by andrewfrench**
## The Problem/Issue/Bug:
#1177: Naive error checking caused nil pointer dereference panics when the error returned was indicating something other than the file not existing.
 
## How this PR Solves The Problem:
This change prevents the panic by expanding the error case to _any_ error value, not just those indicating the file doesn't exist. In the specific case encountered in #1177, this means that if the file exists, but ddev doesn't have permissions to read or edit it, we won't try to.

## Manual Testing Instructions:
- `mkdir -p panic/sites/default`
- `cd panic`
- `sudo chown root sites`
- `sudo chmod 000 sites`
- `ddev config --project-name panic --docroot . --project-type drupal8`
- Ensure that ddev warns that it doesn't have permissions to write config files and .gitignore, but no panic is encountererd

## Related Issue Link(s):
#1177

### CODE REVIEW

File: pkg/ddevapp/drupal.go [hunk 1]
```diff
@@ -653,8 +653,7 @@ func drupalEnsureWritePerms(app *DdevApp) error {
 
 	for _, o := range makeWritable {
 		stat, err := os.Stat(o)
-		// If the file doesn't exist, don't try to set the permissions.
-		if os.IsNotExist(err) {
+		if err != nil {
 			continue
```
Comment (rfay) [inline pkg/ddevapp/drupal.go]: I'm pretty sure this should emit a util.Warning*(), since we're skipping by here and never hitting anything that will give them a warning about what's happened.

**Comment by andrewfrench** [comment]
I've addressed the comments in here that have to do with better logging and warning, and have improved a few warning messages that were already returning a PathError and don't need to restate the path to the file in question.

I think refactoring this is a good idea and I support it, but I'm not really open to doing that as a hop-on for this PR - I think it's best to let this solve the original issue and open another to capture what needs to be done to consolidate logic moving forward.

**Comment by rfay** [comment]
Oops, I messed up. With this we get warnings about files that don't exist, we'll need to not emit warnings for a file that doesn't exist.
```
Unable to ensure write permissions: stat /Users/rfay/workspace/nblewis.com/sites/default/settings.ddev.php: no such file or directory
Ensuring write permissions for nblewis.com
Unable to ensure write permissions: stat /Users/rfay/workspace/nblewis.com/sites/default/settings.php: no such file or directory
Unable to ensure write permissions: stat /Users/rfay/workspace/nblewis.com/sites/default/settings.ddev.php: no such file or directory
Unable to ensure write permissions: stat /Users/rfay/workspace/nblewis.com/sites/default/services.yml: no such file or directory
No settings.php file exists, creating one
```
