### PR TITLE
validate sitenames, validate config during init, fixes #86

### LINKED ISSUE #86: Sanitize Site Names
## What happened:
I created a site with sitename with a suspected invalid character. When I attempted to take the site through the workflow, the site spin-up failed with an Exit code 1.

## What you expected to happen:
I expected the site to come up all the way.

## How to reproduce it (as minimally and precisely as possible):
Create a folder with an invalid site name and use it as the default site name or just run `ddev config` and try plugging in a site name with invalid characterts.

## Anything else do we need to know:
People might have folder names that we have to sanitize (e.g. they interact with their folders through Finder and use invalid characters in the folder name. In general, the sitename input should be sanitized.

## Related source links or issues:
Console Output

```
➜  src mkdir invalid-drud-site\?
➜  src cd invalid-drud-site\?
➜  invalid-drud-site? cp -R ../drud-d7/docroot .
➜  invalid-drud-site? ddev config
Creating a new ddev project config in the current directory (/Users/csterling/src/invalid-drud-site?)
Once completed, your configuration will be written to /Users/csterling/src/invalid-drud-site?/.ddev/config.yaml

Project name (invalid-drud-site?):

The docroot is the directory from which your site is served. This is a relative path from your application root (/Users/csterling/src/invalid-drud-site?)
You may leave this value blank if your site files are in the application root
Docroot Location: docroot
Found a drupal7 codebase at /Users/csterling/src/invalid-drud-site?/docroot
➜  invalid-drud-site? ddev start
Starting environment for invalid-drud-site?...

Adding hostfile entry. You will be prompted for your password.
Password:
Failed to start invalid-drud-site?: exit status 1
```

### PR DESCRIPTION
**Pull request by tannerjfco**
## The Problem:
#86 OP we currently accept site names allowing any/all characters. This doesn't work out so well for domain names, and attempting to start a site whose sitename contains invalid characters for a domain will result in the site failing to start.

## The Fix:
This PR introduces validation of the site name value. Site names will now be validated as hostnames per RFC 1123. If the working directory name does not validate, it will not be suggested to the user. If the user supplies an invalid site name during "ddev config", they will be re-prompted for the site name.

This also introduces a Validate() method for config that runs during App.Init(), which will validate hostname, docroot, and apptype. If any of these values are invalid, an error will be returned to the user instructing them to resolve the invalid configuration.

## The Test:
The case in OP should no longer be reproducible:
- mkdir invalid-drud-site\?
- cd invalid-drud-site\?
- ddev config, there should be no suggested site name
- Provide a sitename with invalid characters. You should be prompted to re-enter the sitename.
- ddev start. it should not fail

You can also test config validation on start by manually setting values in config.yaml and running "ddev start:
- Entering a sitename with invalid characters and running "ddev start" should result in an error saying the sitename is invalid.
- Entering a non-existent docroot path should result in an error saying the docroot path does not exist.
- Entering an invalid apptype should result in an error saying the apptype is invalid.

## Automation Overview:

Introduced a test for the new config Validate() method.

## Related Issue Link(s):
#86

### CODE REVIEW

File: pkg/ddevapp/config.go [hunk 1]
```diff
@@ -31,6 +33,9 @@ const DDevTLD = "ddev.local"
 // AllowedAppTypes lists the types of site/app that can be used.
 var AllowedAppTypes = []string{"drupal7", "drupal8", "wordpress"}
 
+// Regexp pattern for alphanumeric + dashes
+var re = regexp.MustCompile(`[^a-zA-Z0-9_-]+`)
```
Comment (rfay) [inline pkg/ddevapp/config.go]: Don't you want '^[a-zA-Z0-9_-]+$' ?

Comment (tannerjfco) [inline pkg/ddevapp/config.go]: This doesn't seem to produce the result I'm after: https://play.golang.org/p/X9Q0TrjLLw

Comment (rfay) [inline pkg/ddevapp/config.go]: I think I misunderstood the intent - I was giving a validation string, not a replacement string.

File: pkg/ddevapp/config.go [hunk 2]
```diff
@@ -31,6 +33,9 @@ const DDevTLD = "ddev.local"
 // AllowedAppTypes lists the types of site/app that can be used.
 var AllowedAppTypes = []string{"drupal7", "drupal8", "wordpress"}
 
+// Regexp pattern to match any non-alphanumeric characters (except dashes) so they can be replaced.
+var re = regexp.MustCompile(`[^a-zA-Z0-9_-]+`)
```
Comment (beeradb) [inline pkg/ddevapp/config.go]: Any reason to not just do a full hostname regex here, since that's our end goal?

It's a lot more wordy, but a full hostname REGEX based on RFC 1123 would be: `^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])$` according to https://stackoverflow.com/a/106223

File: pkg/ddevapp/config.go [hunk 3]
```diff
@@ -154,16 +162,20 @@ func (c *Config) Config() error {
...
 			c.Name = filepath.Base(dir)
+			c.Name = re.ReplaceAllString(c.Name, "")
 		}
 	}
 
 	namePrompt = fmt.Sprintf("%s (%s)", namePrompt, c.Name)
 	// Define an application name.
 	fmt.Print(namePrompt + ": ")
 	c.Name = util.GetInput(c.Name)
+	c.Name = re.ReplaceAllString(c.Name, "")
```
Comment (beeradb) [inline pkg/ddevapp/config.go]: We also do this on line 137 - https://github.com/drud/ddev/pull/339/files#diff-1bfb3bdcc7f3b22b48ea905d60583d2dR137

Any reason we are repeating it?

**Comment by rickmanelius** [comment]
I see merit in Brad's comment about validation instead of substitution. Perhaps there is a better middle ground and we can use this as an opportunity to help guide an end-user. If someone tries to use ☃ as a valid UTF-8 character, we simply warn the user "We enforce site names to be alphanumeric with dashes. We detected your input to include non-supported characters. Would you like us to automatically convert them?" Or we can be a little more heavy handed "We automatically converted 'my-☃-site' to 'my--site'". That way we're not roadblocking the user but making them aware of what happened.

**Comment by tannerjfco** [comment]
Given that config can be manually written I think it does make sense to perform validation on start. I could also see how stripping the sitename could be unexpected to the user, and realistically it's a simple correction to make, and we want them to make it so that the written configuration is valid. I'll move forward on the validation approach as suggested.

File: pkg/ddevapp/config.go [hunk 4]
```diff
@@ -178,6 +177,29 @@ func (c *Config) Config() error {
 	return nil
 }
 
+// Validate ensures the configuraton meets ddev's requirements.
+func (c *Config) Validate() error {
+	// validate docroot
+	fullPath := filepath.Join(c.AppRoot, c.Docroot)
+	if _, err := os.Stat(fullPath); os.IsNotExist(err) {
+		return fmt.Errorf("no directory could be found at %s. Please enter a valid docroot in your configuration", fullPath)
```
Comment (beeradb) [inline pkg/ddevapp/config.go]: Absolutely love this. Thanks so much for adding it.

This might fall outside of this PR, but should we also use your app type detection and issue a warning if a known app type isn't detected/doesn't match configured app type?

Happy to push that one down the road if you would prefer, it's just a check that comes to mind as potentially useful as I look at these others.

Comment (tannerjfco) [inline pkg/ddevapp/config.go]: I'm a bit wary of doing this, as it means our detection would need to be more robust than it currently is. The big problem case I think of off-hand is that WordPress allows for a custom core directory, and a site using this structure would fail to detect as a WordPress site.

Comment (beeradb) [inline pkg/ddevapp/config.go]: My thinking was that it would just be a warning about a potential problem rather than actually prevent the site from starting, but I can accept your answer either way :)

**Comment by rickmanelius** [comment]
@tannerjfco I know you're moving onto the pre/post hook feature #183, but this would probably be a  good WIP item to close out.

**Comment by rickmanelius** [comment]
So tempted to hit the big green merge button! :)
